import React from 'react';
import {
  Box,
  Paper,
  Typography,
  Table,
  TableBody,
  TableCell,
  TableContainer,
  TableHead,
  TableRow,
  Chip,
  Button,
  Divider,
} from '@mui/material';
import {
  Email as EmailIcon,
  ContentCopy as CopyIcon,
} from '@mui/icons-material';
import { toast } from 'sonner';

interface EmailTemplateProps {
  title: string;
  dateRange: string;
  data: any[];
  columns: { key: string; label: string; format?: (value: any) => string }[];
  summary?: { label: string; value: string }[];
  onSend?: () => void;
}

/**
 * Email Template Preview Component
 * Generates a preview of how the email will look when sent
 */
const EmailTemplate: React.FC<EmailTemplateProps> = ({
  title,
  dateRange,
  data,
  columns,
  summary,
  onSend,
}) => {
  const copyToClipboard = () => {
    const text = generateEmailText();
    navigator.clipboard.writeText(text);
    toast.success('Email content copied to clipboard');
  };

  const generateEmailText = () => {
    let text = `${title}\n`;
    text += `Date Range: ${dateRange}\n`;
    text += `\n`;
    
    if (summary && summary.length > 0) {
      text += 'Summary:\n';
      summary.forEach(item => {
        text += `- ${item.label}: ${item.value}\n`;
      });
      text += `\n`;
    }
    
    text += 'Details:\n';
    text += columns.map(col => col.label).join(' | ') + '\n';
    text += '-'.repeat(50) + '\n';
    
    data.forEach(row => {
      text += columns.map(col => {
        const value = row[col.key];
        return col.format ? col.format(value) : value;
      }).join(' | ') + '\n';
    });
    
    return text;
  };

  return (
    <Paper sx={{ p: 3, maxWidth: 800 }}>
      {/* Email Header */}
      <Box sx={{ mb: 3 }}>
        <Typography variant="h5" sx={{ fontWeight: 700, color: 'primary.main' }}>
          {title}
        </Typography>
        <Typography variant="body2" color="text.secondary">
          Generated on {new Date().toLocaleDateString()} | Period: {dateRange}
        </Typography>
      </Box>

      <Divider sx={{ my: 2 }} />

      {/* Summary Section */}
      {summary && summary.length > 0 && (
        <Box sx={{ mb: 3 }}>
          <Typography variant="h6" sx={{ fontWeight: 600, mb: 2 }}>
            Summary
          </Typography>
          <Box sx={{ display: 'flex', gap: 2, flexWrap: 'wrap' }}>
            {summary.map((item, index) => (
              <Chip
                key={index}
                label={`${item.label}: ${item.value}`}
                color="primary"
                variant="outlined"
                sx={{ fontWeight: 500 }}
              />
            ))}
          </Box>
        </Box>
      )}

      {/* Data Table */}
      <Box sx={{ mb: 3 }}>
        <Typography variant="h6" sx={{ fontWeight: 600, mb: 2 }}>
          Details
        </Typography>
        <TableContainer>
          <Table size="small">
            <TableHead>
              <TableRow sx={{ bgcolor: 'action.hover' }}>
                {columns.map((col) => (
                  <TableCell key={col.key} sx={{ fontWeight: 700 }}>
                    {col.label}
                  </TableCell>
                ))}
              </TableRow>
            </TableHead>
            <TableBody>
              {data.slice(0, 10).map((row, index) => (
                <TableRow key={index} hover>
                  {columns.map((col) => (
                    <TableCell key={col.key}>
                      {col.format ? col.format(row[col.key]) : row[col.key]}
                    </TableCell>
                  ))}
                </TableRow>
              ))}
            </TableBody>
          </Table>
        </TableContainer>
        {data.length > 10 && (
          <Typography variant="caption" color="text.secondary" sx={{ mt: 1, display: 'block' }}>
            ... and {data.length - 10} more rows (see full report in attachment)
          </Typography>
        )}
      </Box>

      <Divider sx={{ my: 2 }} />

      {/* Footer */}
      <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
        <Typography variant="caption" color="text.secondary">
          Generated by EverGreen Inventory System
        </Typography>
        <Box sx={{ display: 'flex', gap: 1 }}>
          <Button
            variant="outlined"
            size="small"
            startIcon={<CopyIcon />}
            onClick={copyToClipboard}
          >
            Copy Text
          </Button>
          {onSend && (
            <Button
              variant="contained"
              size="small"
              startIcon={<EmailIcon />}
              onClick={onSend}
            >
              Send Email
            </Button>
          )}
        </Box>
      </Box>
    </Paper>
  );
};

export default EmailTemplate;
