// Maintained source for focused skills; taxonomy concerns map to these cards.
const rows = [
  ['product', 'Product and requirements', 'Product,Requirements,Risk,Stakeholder Communication', 'Must-have', 'Translate textile business needs into verifiable handoffs.', 'New feature, unclear request or changed acceptance criteria', 'User request; CONTEXT.md; PARITY_REGISTER.md', 'Identify staff/customer actor and affected handoff.;Trace the existing screen, endpoint and ledger owner.;Write measurable acceptance criteria and unresolved assumptions.;Prioritize data integrity and recovery before expansion.', 'Every criterion has an evidence source; no planned capability presented as delivered', 'Scoped brief and acceptance matrix', 'Acceptance criteria verified; unresolved assumptions', 'Invented personas or release readiness; cosmetic work masking broken handoffs', 'Conditional: business owner decides pricing, scope conflicts and acceptance', 'architecture,quality'],
  ['architecture', 'Architecture and scale', 'Architecture,Scalability', 'Must-have', 'Evolve the modular application across business, site and tenant boundaries.', 'New module, shared data ownership or deployment topology change', 'Schema; AppModule; desktop main/preload; target scale', 'Map current module and persistence boundaries.;Identify canonical writes and site/tenant ownership.;Compare a modular monolith with alternatives using measured needs.;Record an ADR with rollout and rollback implications.', 'No microservice or sync complexity without a concrete requirement; tenancy remains unverified until isolation tests pass', 'ADR and boundary diagram', 'Cross-boundary writes; ADR assumptions resolved', 'Shared global records exposed across tenants; accidental distributed transactions', 'Conditional: owner approves topology, tenancy and material cost decisions', 'data,security,release'],
  ['ux', 'Business UX and accessibility', 'UX/UI,Accessibility', 'Must-have', 'Make receipt-to-payment usable and truthful on narrow and wide screens.', 'Workflow, navigation, form or dashboard change', 'User task; existing MUI components; API states', 'Walk the handoff and its error/recovery path.;Reuse theme tokens and accessible controls.;Implement loading, empty, stale, failure and permission states.;Check keyboard focus, labels, narrow layouts, dark mode and reduced motion.', 'No invented zero balances or healthy statuses; actions remain operable by keyboard; future accessibility conformance needs an audit', 'UI change and interaction evidence', 'Task completion; inaccessible controls; hidden failure states', 'Clickable non-buttons; clipped amounts; motion without a reduced-motion path', 'Conditional: owner reviews materially changed business steps', 'frontend,quality,localization'],
  ['frontend', 'React data flows', 'Frontend,Web,Error Handling', 'Must-have', 'Keep React screens consistent with server records and navigation.', 'Query, mutation, route or staff/public screen change', 'App.tsx; utils/api.ts; TanStack query keys; endpoint contract', 'Trace API base URL and authentication behavior.;Use stable cache keys and invalidate affected summaries after writes.;Prevent repeated submission and expose errors without losing user input.;Verify browser Back, refresh, deep links and stale data behavior.', 'No client-only authorization or fallback success; shop data cannot expose staff/customer internals', 'Components and focused interaction tests', 'Failed requests surfaced; mutation-to-summary consistency', 'Hardcoded operational badges; swallowed exceptions; duplicate submissions', 'No for authorized reversible code changes', 'ux,api,security'],
  ['api', 'Nest API contracts', 'Backend,API', 'Must-have', 'Keep endpoints validated, scoped and usable through desktop and web paths.', 'Endpoint or business mutation change', 'Controller; service; DTO; Swagger; guards', 'Trace global and route guards.;Define DTO validation and explicit response/errors.;Keep state changes in service transactions and document replay behavior.;Verify proxy /api/backend and direct API server selection.', 'Malformed/unknown fields rejected on DTO routes; role/site/tenant checks tested; Swagger examples use synthetic data', 'Controller/service changes and contract tests', 'Typed write routes; authorization denials tested', 'Any bodies treated as validated; write retries creating duplicates', 'Conditional: incompatible contracts or live migrations', 'data,security,quality'],
  ['data', 'Ledger and database integrity', 'Database,Migration', 'Must-have', 'Preserve stock, invoice and payment invariants through changes.', 'Schema, stock, invoice, payment, cancellation or migration work', 'Prisma schema; commerce service; legacy paths; disposable fixture', 'Identify canonical writer and duplicate paths.;Define quantity and currency invariants, rounding and reversals.;Use atomic changes and idempotent replay semantics.;Test partial payment, cancellation, insufficient stock and concurrent writes.;Prepare reconciliation and backup/restore evidence before migration.', 'No operational db push/reset; balances reconcile; failed operations leave no partial records', 'Migration proposal, invariant tests and reconciliation report', 'Unexplained stock/currency delta must be zero; duplicate effects', 'Parallel ledger writes; floating-point drift; guessed data conversion', 'Conditional: exact approval for live migration or record mutation', 'api,recovery,quality'],
  ['security', 'Identity and security boundaries', 'Auth,Security', 'Must-have', 'Protect staff access, public routes and tenant data.', 'Auth, session, permissions, public API or dependency change', 'Guards; auth/session services; roles; diff; tenant model proposal', 'Threat-model entry points and protected data.;Test viewer/modifier/admin and unknown roles at the API.;Test revoked sessions, cross-user and cross-tenant object access.;Review validation, output encoding, secret handling and public rate limits.;Record findings before merge or release.', 'No confirmed high-impact auth/data exposure left unresolved for release; no secrets in artifacts', 'Threat model and evidence-based findings', 'Boundary test coverage; unresolved exploitable findings', 'Trusting UI permission checks; static production secrets; tenant ID from an untrusted body', 'Conditional: owner decides risk exceptions; agent never grants itself an exception', 'api,data,privacy'],
  ['privacy', 'Privacy, compliance and legal evidence', 'Privacy,Compliance,Legal', 'Must-have', 'Turn owner-approved obligations into testable handling of business and staff data.', 'Personal data, retention, export, tax/provider or licensing change', 'Data inventory; business jurisdictions; approved obligations; license inventory', 'Inventory customer, employee, authentication and invoice fields.;Ask for jurisdiction/retention decisions when missing.;Verify current authoritative requirements before legal implementation.;Minimize collection and redact logs/test fixtures.;Document retention/export/delete design and preserve required financial history.', 'No unsupported legal/certification claims; owner review for legal interpretation; no real PII in evaluation data', 'Data map, obligation register and implementation evidence', 'Unowned sensitive fields; overdue retention decisions', 'Assuming every regulation applies; silently deleting financial history', 'Yes for legal applicability, retention and policy acceptance', 'security,data,operations'],
  ['localization', 'English and Tamil workflows', 'i18n', 'Should-have', 'Keep business actions and documents understandable across supported languages.', 'New visible text, locale formatting or print changes', 'packages/i18n; invoice/PDF text; user language preference', 'Use shared translations where supported.;Check amounts, units, dates and long Tamil labels.;Verify forms, errors, saved invoice PDF and print layout.;Record missing translations without claiming full bilingual coverage.', 'No truncated invoice amounts or untranslated critical errors', 'Translation changes and locale QA record', 'Critical strings covered; layout defects', 'Translating stored identifiers; inconsistent date/currency interpretation', 'Conditional: native-language reviewer for customer-facing wording', 'ux,documents,quality'],
  ['performance', 'Performance and capacity', 'Performance', 'Should-have', 'Measure bottlenecks before scaling infrastructure.', 'Slow dashboard, large inventory or increased site/tenant load', 'Representative synthetic data; timings; bundle/build reports', 'Capture baseline query, API and render timings.;Inspect query cardinality, indexing, payloads and large lazy chunks.;Apply the smallest measured improvement.;Repeat the same workload and document capacity limits.', 'No performance claim without workload and before/after evidence; no load testing live business data', 'Benchmark and targeted improvement', 'p95 latency; payload bytes; bundle size; memory', 'Caching tenant data without tenant keys; sharding before measurement', 'Conditional: external load tests or infrastructure spend', 'architecture,data,quality'],
  ['quality', 'Critical-path verification', 'Testing,Code Quality', 'Must-have', 'Verify business outcomes and recovery behavior, not implementation wording.', 'Feature, bug fix or release candidate', 'Acceptance criteria; diff; disposable database; test commands', 'Choose tests for changed invariants and regressions.;Exercise success, validation, role denial, timeout and replay paths.;Run relevant TypeScript/build checks and focused tests.;Perform action-level browser/desktop checks where affected.;Record exact results and distinguish failures from missing capabilities.', 'No fabricated green gates; money/stock paths need meaningful tests; schema checks alone do not prove behavior', 'Test evidence and unresolved defects', 'Critical scenarios passed; regressions; flaky tests', 'Broad snapshots instead of invariants; fixtures using operational records', 'Conditional: release acceptance and unresolved risk', 'data,frontend,security'],
  ['release', 'Delivery and release engineering', 'CI/CD,Infrastructure,Release', 'Must-have', 'Produce reproducible, reversible desktop and hosted releases.', 'CI change, release candidate, hosting or installer work', 'Lockfile; build commands; deployment target; signing owner; migration plan', 'Build from reproducible dependencies and record artifact hashes.;Run required critical-path and boundary checks.;Prepare hosted routing/configuration and desktop package verification.;Attach backup/migration/rollback evidence.;Request exact production/publishing approval, then verify health and business smoke checks.', 'No deployment based only on compilation; no secrets in artifacts; no unsigned claim of desktop trust', 'Release manifest, pipeline and rollback runbook', 'Deploy failure rate; rollback time; artifact reproducibility', 'Shipping dev secrets; stale bundled backend; mixing per-tenant environments', 'Yes for production deployment, signing/publishing or paid infrastructure', 'quality,recovery,operations'],
  ['operations', 'Reliability and observability', 'Reliability,Observability,Logging,Monitoring,Alerting,Incident Response', 'Must-have', 'Expose meaningful failures and recover service without corrupting records.', 'Health, logging, alert, scheduled job or incident work', 'Health controller/service; redacted logs; owner; target SLO', 'Trace request/job correlation and distinguish checks from assumed status.;Define useful dependency health and timestamp freshness.;Redact tokens, personal data and financial details.;Connect actionable alerts to an owner and runbook.;During incidents preserve evidence, limit impact and reconcile uncertain writes.', 'Unknown status is not healthy; alerts have response instructions; recovery does not blindly replay financial writes', 'Health/alert changes and incident runbook', 'Detection/recovery time; stale health; actionable alert ratio', 'Success responses for failed processors; noisy unowned alerts', 'Conditional: live operational changes and external incident communications', 'recovery,security,release'],
  ['recovery', 'Backup and disaster recovery', 'Backup/DR', 'Must-have', 'Prove that SQLite and hosted data can be restored consistently.', 'Migration, cutover, release or recovery drill', 'Database location; active writers; backup mechanism; RPO/RTO owner', 'Identify SQLite journal mode and a consistent online backup method.;Preserve a manifest and checksums without exposing records.;Restore into an isolated location.;Reconcile row counts, stock balances, invoices and payment totals.;Measure restore time and record cutover/rollback conditions.', 'File copying an active database alone is not proof of a consistent backup; restore drill required before live cutover', 'Verified backup manifest and restore evidence', 'Measured recovery time and data loss window', 'Overwriting the only backup; restoring over live records without approval', 'Conditional: operational backup access, live restore or migration', 'data,operations,release'],
  ['documents', 'Documentation and developer setup', 'Documentation,DevEx', 'Must-have', 'Keep setup, guides and API/PDF behavior aligned with the application.', 'Workflow, service URL, configuration or generated document change', 'README; QUICK_START; Tutorial; BusinessFlowGuide; Swagger; packages/pdf', 'Trace commands and links to actual scripts/routes.;Use one shared source for repeated workflow instructions.;Document configured ports, bootstrap secrets and new-vs-existing database steps.;Verify saved invoice data and shared totals drive documents.;Mark legacy guides and future features clearly.', 'No default shared passwords; no misleading release claims; setup does not mutate existing data automatically', 'Updated guides, links and setup diagnostics', 'Broken links; reproducible setup; document/record differences', 'Copying framework README boilerplate; recalculating invoice totals differently in PDF', 'No for authorized documentation; conditional for changing invoice semantics', 'data,localization,quality'],
  ['dependencies', 'Dependency and maintenance hygiene', 'Dependencies,Maintenance', 'Must-have', 'Keep the monorepo supportable without uncontrolled upgrades.', 'Dependency update, technical debt or framework change', 'Lockfile; manifests; usage sites; advisory evidence', 'Identify affected workspaces and runtime compatibility.;Read authoritative release/advisory information for proposed changes.;Choose bounded updates and preserve reproducibility.;Test impacted web, API and desktop behavior.;Document unresolved advisory or migration risks.', 'No blanket major upgrades or audit-fix force without review; runtime support verified', 'Bounded dependency diff and compatibility evidence', 'Known applicable advisories; upgrade regressions', 'Updating bundled desktop code independently; treating audit counts as exploitability proof', 'Conditional: breaking architecture or licensing changes', 'quality,security,desktop'],
  ['analytics', 'Business reporting and optional forecasting', 'Analytics,AI/ML', 'Should-have', 'Produce trustworthy reports and evaluate automation against real evidence.', 'KPI, report, baseline forecast or AI proposal', 'Canonical ledger definitions; data window; consent/retention requirements', 'Define each metric and source records.;Reconcile totals and handle empty/stale windows.;For forecasts, compare against a trailing baseline with held-out data.;Expose uncertainty and prohibit autonomous financial decisions.;Use the host ML skill before actual model training/evaluation work.', 'No AI label on a simple average; no PII sent to an external model without approved handling', 'Metric definitions and evaluation report', 'Ledger/report delta; forecast error versus baseline', 'Fake KPIs; leakage between training/evaluation windows', 'Conditional: data use, paid model services or automated decisions', 'data,privacy,quality'],
  ['desktop', 'Desktop and platform support', 'Desktop,Mobile', 'Must-have', 'Keep the Electron delivery aligned with hosted workflows and explicit offline limits.', 'Installer, preload/IPC, updater, local backend or offline change', 'apps/desktop; API base URL; supported Windows versions; sync decision', 'Trace bundled web/backend versions and local database location.;Review Electron process isolation and IPC contracts.;Test install, launch, update and rollback on a disposable profile.;Decide online-hosted versus local ownership before offline writes.;Treat native mobile as a separate optional product, not implied by responsive web.', 'No silently divergent schemas or bidirectional sync; updates preserve operational data', 'Platform compatibility and package verification record', 'Version skew; installation success; sync conflicts', 'Editing packaged backend as a second source of truth; untrusted IPC', 'Conditional: installer publishing, signing and destructive updates', 'release,security,data'],
  ['integrations', 'External integration contracts', 'Integrations', 'Should-have', 'Add providers without duplicate financial effects or unsupported status claims.', 'Payment, accounting, tax, email or device provider integration', 'Approved provider; sandbox; webhook/auth specification; retries', 'Verify current primary provider docs and supported contract.;Use sandbox credentials and validate signatures/replay windows.;Persist correlation and idempotency keys.;Handle partial failure and read-back before retries.;Distinguish internal creation from provider acceptance.', 'No claimed delivery/filing success without provider evidence; no live test sends without authorization', 'Adapter, contract tests and failure runbook', 'Duplicate effects; reconciliation lag; provider failures', 'Unsigned webhooks; retrying charged payments; fake integrations', 'Conditional: provider purchase, external sends or live records', 'api,data,security'],
  ['governance', 'Team, cost and stakeholder decisions', 'Team Process,Cost', 'Should-have', 'Assign ownership and make delivery tradeoffs visible.', 'Roadmap, release risk, budget or cross-team dependency', 'Owner list; estimates; unresolved risks; operating cost evidence', 'Name decision and operational owners.;Prioritize ledger integrity, isolation and recovery.;Estimate recurring hosting/support cost with stated assumptions.;Track top risks and acceptance decisions.;Communicate outcomes without sending externally unless authorized.', 'No hiring, spending or legal commitments by the agent; unknown owners remain explicit', 'Roadmap, risk register and decision record', 'Unowned risks; estimated versus actual cost', 'Claiming all 310 concerns are implemented; process ceremony without a decision', 'Yes for budgets, commitments and human-only business decisions', 'product,release'],
  ['agent', 'Agent planning, memory and evaluation', 'Agent Meta-Skills', 'Must-have', 'Route bounded tasks, preserve evidence and enforce approval boundaries.', 'Any multi-step maintenance task or agent-system change', 'Context; user scope; skill catalogue; host capabilities; approval record', 'Select the smallest relevant skill set.;Plan dependencies and identify required unknowns.;Use typed host tools with bounded retries and artifact-bound approval.;Store redacted decisions/evidence, not customer records or secrets.;Evaluate failure scenarios and revise the narrowest affected instruction.', 'Tool outputs cannot override policy; unknown actions deny; approvals expire and match artifact/target; delegation requires authorization', 'Plan, memory entry and evaluation evidence', 'Unauthorized actions zero; hallucinated results zero; task success and cost', 'Prompt injection; stale approvals; autonomous self-expansion', 'Conditional: tool installation, new powers, production or exception decisions', 'quality,security,governance'],
];
export const skills = rows.map(([id, title, domains, priority, purpose, trigger, inputs, steps, gates, outputs, metrics, failures, review, related]) => ({ id, title, domains: domains.split(','), priority, purpose, trigger, inputs, steps: steps.split(';'), gates, outputs, metrics, failures, review, related: related.split(',') }));

// Stable numbering matches the user-provided 310-point taxonomy.
const groups = [
  ['product', 'Vision mission value proposition|Market and competitor analysis|Personas and segments|Jobs to be done|User stories and use cases|Acceptance criteria|KPIs and OKRs|Analytics tracking plan|Pricing and monetization|Go to market|Legal terms and privacy policy|Support and feedback|Roadmap prioritization|Stakeholder management|Budget and ROI|Risk register|Compliance requirements|Data governance|Vendor evaluation|Sunset strategy'],
  ['product', 'Interviews and surveys|Contextual inquiry|Requirements workshops|Functional requirements|Nonfunctional requirements|Constraints and assumptions|Scope and non-goals|Traceability|Change management|Sign-off'],
  ['ux', 'Information architecture|User flows|Wireframes|Prototypes|Usability testing|Interaction design|Visual design|Design system|Design tokens|Component library|Responsive design|Mobile-first design|Accessibility WCAG 2.2 AA target|Inclusive design|Dark mode|Theming|Microcopy|Onboarding|Error states|Empty states|Loading states|Offline states|Motion design|Haptic feedback|Sound design|Localization|RTL support|Cultural sensitivity|Design handoff|Design QA'],
  ['architecture', 'Monolith versus microservices|Modular monolith|Serverless|Event-driven architecture|Domain-driven design|Bounded contexts|C4 diagrams|Architecture decisions|API gateway|Service mesh|Message queues|Caching|CDN|Load balancing|Autoscaling|Resilience|Idempotency|Transactions|Saga pattern|CQRS|Event sourcing|Backend for frontend|GraphQL federation|gRPC|WebSockets|Webhooks|Batch processing|Stream processing|Search|Recommendations|AI ML integration|Feature flags|Configuration'],
  ['data', 'SQL versus NoSQL|Schema design|Normalization|Indexing|Migrations|Seeding|Transactions|ACID|CAP tradeoffs|Sharding|Partitioning|Replication|Backup|Restore|Disaster recovery|Retention|Deletion|PII handling|Encryption|Masking|Anonymization|Data warehouse|Data lake|ETL ELT|Analytics|Reporting|BI'],
  ['security', 'Threat modeling|OWASP Top 10|SAST|DAST|SCA|SBOM|Pen testing|Bug bounty|Secrets management|Key rotation|Encryption at rest|Encryption in transit|TLS|mTLS|IAM|RBAC|ABAC|ReBAC|MFA|SSO|OAuth|OIDC|SAML|Sessions|JWT|CSRF|XSS|SQL injection|SSRF|IDOR|Rate limiting|Bot protection|DDoS protection|WAF|Audit logs|GDPR|CCPA|HIPAA|PCI DSS|SOC2|ISO 27001|FedRAMP|Accessibility compliance|Licensing|IP'],
  ['quality', 'Test strategy|Test pyramid|Unit tests|Integration tests|Contract tests|End-to-end tests|Smoke tests|Regression tests|Performance tests|Load tests|Stress tests|Soak tests|Security tests|Accessibility tests|Usability tests|Visual regression|Snapshot tests|Mutation tests|Property-based tests|Fuzz tests|Chaos engineering|Test data|Test environments|CI gates|Coverage|Static analysis|Linting|Formatting|Type checking|Code review'],
  ['release', 'Git workflow|Branching|PR process|CI pipeline|CD pipeline|Infrastructure as code|Terraform|Ansible|Kubernetes|Docker|Helm|Serverless|Cloud providers|Environment promotion|Blue green|Canary|Rolling updates|Rollback|Feature flags|Release notes|Semantic versioning|Changelog|Artifact repository|Container registry|CI secrets|Configuration|Monitoring|Logging|Tracing|Metrics|Dashboards|Alerts|SLO SLI SLA|Error tracking|APM|Uptime monitoring|On-call|Runbooks|Incidents|Postmortems|Capacity planning|Cost optimization|FinOps|Backup restore drills|DR drills'],
  ['agent', 'Goal setting|Planning|Task decomposition|Tool use|Memory|Context management|Retrieval|Reflection|Self-critique|Self-evaluation|Guardrails|Safety|Alignment|Human in loop|Approval workflows|Escalation|Uncertainty|Ambiguity|Conflict resolution|Prioritization|Resource management|Time management|Cost management|Agent logging|Agent observability|Debugging|Error recovery|Retries|Fallbacks|Multi-agent coordination|Role specialization|Communication protocols|Shared state|Skill versions|Evaluation harness|Benchmarks|Red teaming|Adversarial tests|Continuous learning|Feedback loops'],
  ['governance', 'Team structure|Roles|Responsibilities|Communication|Meetings|Documentation|Knowledge sharing|Onboarding|Mentoring|Performance reviews|Hiring|Culture|Agile Scrum Kanban|Estimation|Velocity|Retrospectives|Stakeholder communication|Reporting|Budgeting|Procurement'],
  ['architecture', 'Native mobile app stores push offline permissions|Web SEO PWA browser cookies|Desktop updates signing OS integration|Embedded IoT firmware OTA sensors|Blockchain Web3|Game development|API integrations|Legacy migration and cutover|Maintenance and dependencies|AI ML lifecycle'],
];
const optional = new Set([2,8,9,10,19,21,22,23,33,34,42,53,55,57,63,64,65,67,69,70,71,72,73,74,75,79,80,81,82,83,84,85,86,87,88,90,91,92,102,103,104,105,113,114,115,116,117,120,124,126,127,128,134,137,138,140,141,142,143,152,153,154,156,157,159,160,161,175,176,177,181,182,183,184,185,186,201,202,203,204,205,206,207,210,211,212,214,218,219,224,230,236,238,270,271,285,289,290,291,293,295,301,304,307,310]);
const notApplicable = new Set([54,158,162,305,306]);
const overrides = {
  privacy: [11,17,18,109,110,111,112,113,114,156,157,158,159,160,161,162,163,164,165],
  analytics: [7,8,90,91,118,119,120,310],
  governance: [9,10,14,15,19,20,237,238],
  localization: [56,57,58],
  data: [77,78,98,99,100,101,308],
  recovery: [106,107,108,239,240],
  performance: [72,73,74,75,97,174,175,176,177,236],
  operations: [76,155,222,223,224,225,226,227,228,229,230,231,232,233,234,235],
  desktop: [301,303],
  frontend: [49,50,51,52,89,302],
  integrations: [86,304,307],
  documents: [59,215,217,286,287,288],
  dependencies: [125,126,309],
};
let id = 0;
export const taxonomy = groups.flatMap(([skill, titles]) => titles.split('|').map(title => {
  const number = ++id;
  const owner = Object.entries(overrides).find(([, ids]) => ids.includes(number))?.[0] || skill;
  const applicability = notApplicable.has(number) ? 'Not applicable' : optional.has(number) ? 'Optional' : 'Required';
  const priority = applicability === 'Not applicable' ? "Won't-have" : applicability === 'Optional' ? 'Could-have' : ['localization', 'performance', 'analytics', 'integrations', 'governance'].includes(owner) ? 'Should-have' : 'Must-have';
  const reason = applicability === 'Not applicable' ? 'No corresponding product requirement in the confirmed textile ERP scope; revisit if that scope changes.' : applicability === 'Optional' ? 'Depends on measured scale, provider choice, legal applicability or a separately approved feature; not a prerequisite by name alone.' : `Needed for ${skills.find(item => item.id === owner).purpose.toLowerCase()}`;
  return { id: number, title, skill: owner, applicability, priority, reason };
}));
