import { mkdir, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { skills, taxonomy } from './catalog.mjs';
const root = fileURLToPath(new URL('.', import.meta.url));
if (taxonomy.length !== 310) throw new Error(`Expected 310 concerns, found ${taxonomy.length}`);
for (const s of skills) {
  const dir = `${root}/skills/${s.id}`;
  await mkdir(dir, { recursive: true });
  const content = `---\nname: evergreen-${s.id}\ndescription: ${s.purpose} Use for ${s.trigger.toLowerCase()}.\n---\n\n# ${s.title}\n\n## Purpose\n${s.purpose}\n\n## When to use / Trigger\n${s.trigger}.\n\n## Inputs\n${s.inputs}.\n\n## Preconditions\nRead [context](../../CONTEXT.md) and the [operating contract](../../SYSTEM_PROMPT.md). Identify the authorized scope and affected canonical records before work. Required inputs that are unknown stay explicit.\n\n## Tools\nUse available repository search, diff/editor, local npm/Node test tools and browser/desktop inspection where relevant. For external or privileged operations verify the host has the capability and authorization; see [tool contracts](../../tools.json).\n\n## Steps\n${s.steps.map((step, i) => `${i + 1}. ${step.trim()}`).join('\n')}\n\n## Checks / Quality Gates\n- ${s.gates}.\n- Report actual checks and unexecuted checks separately.\n\n## Outputs / Artifacts\n${s.outputs}.\n\n## Metrics\n${s.metrics}.\n\n## Failure Modes and Anti-patterns\n${s.failures}.\n\n## Human Review\n${s.review}. Existing exact authorization remains valid; routine reversible work needs no extra checkpoint.\n\n## Related Skills\n${s.related.map(id => `[${id}](../${id}/SKILL.md)`).join(', ')}.\n\n## Example Prompt\nApply evergreen-${s.id} to the current EverGreen task. Start from ${s.inputs}. Produce ${s.outputs.toLowerCase()}, and show evidence for: ${s.gates.toLowerCase()}. Respect the current user scope.\n\n## Priority and omission risk\n${s.priority}. Skipping this work can cause: ${s.failures.toLowerCase()}. Domains: ${s.domains.join(', ')}.\n`;
  await writeFile(`${dir}/SKILL.md`, content);
}
await writeFile(`${root}/skills/index.md`, '# EverGreen skills\n\nFocused cards share related concerns; taxonomy IDs remain individually traceable.\n\n| Skill | Trigger | Priority |\n| --- | --- | --- |\n' + skills.map(s => `| [${s.title}](${s.id}/SKILL.md) | ${s.trigger} | ${s.priority} |`).join('\n') + '\n');
await writeFile(`${root}/domains.md`, '# Domain coverage\n\nRequired means required for the selected target, not already implemented. AI/ML and native mobile are optional portions of otherwise relevant cards.\n\n| Domain | Applicability | Skill | Why / omission risk |\n| --- | --- | --- | --- |\n' + skills.flatMap(s => s.domains.map(domain => `| ${domain} | ${['AI/ML', 'Mobile'].includes(domain) ? 'Optional' : 'Required'} | [${s.title}](skills/${s.id}/SKILL.md) | ${['AI/ML', 'Mobile'].includes(domain) ? 'No approved native mobile or model-training requirement; deferral limits these expansion paths.' : `${s.purpose} Skipping: ${s.failures}.`} |`)).join('\n') + '\n');
await writeFile(`${root}/taxonomy.md`, '# 310-point applicability and priority register\n\nTarget: desktop + hosted, single business → multi-site → multi-business. Optional legal regimes need owner/adviser applicability decisions. Required does not mean delivered. Related points intentionally share cards to avoid conflicting duplicate policy.\n\n| ID | Concern | Applicability | MoSCoW | Skill | Reason / deferral impact |\n| --- | --- | --- | --- | --- | --- |\n' + taxonomy.map(t => `| ${t.id} | ${t.title} | ${t.applicability} | ${t.priority} | [${t.skill}](skills/${t.skill}/SKILL.md) | ${t.reason}${t.applicability === 'Optional' ? ` Deferring ${t.title.toLowerCase()} leaves that specific capability unevaluated until its trigger occurs.` : ''} |`).join('\n') + '\n');
console.log(`Generated ${skills.length} skill cards and ${taxonomy.length} concern decisions.`);
