import React, { useMemo, useState } from 'react';
import { Add as AddIcon, Inventory2 as CatalogueIcon, ReceiptLong as InvoiceIcon, People as CustomerIcon, ShoppingCart as OrderIcon } from '@mui/icons-material';
import { Box, Button, Dialog, DialogActions, DialogContent, DialogTitle, Grid, MenuItem, Paper, Stack, Tab, Tabs, Table, TableBody, TableCell, TableContainer, TableHead, TableRow, TextField, Typography } from '@mui/material';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { toast } from 'sonner';
import api from '../utils/api';

type Item = { id: number; sku: string; name: string; type: string; uom: string; hsnSac?: string; gstRate: number; salePrice: number; reorderLevel: number; stock: { available: number } };
type Customer = { id: number; name: string; phone?: string; gstin?: string; state?: string; balance: number };
type Line = { itemId: number | ''; quantity: string; rate?: string; discount?: string };
const stateNames = ['Tamil Nadu', 'Karnataka', 'Kerala', 'Maharashtra', 'Delhi', 'Gujarat', 'Telangana', 'Andhra Pradesh'];

const CommerceDesk: React.FC<{ initialTab?: number }> = ({ initialTab = 0 }) => {
  const client = useQueryClient(); const [tab, setTab] = useState(initialTab); const [itemOpen, setItemOpen] = useState(false); const [customerOpen, setCustomerOpen] = useState(false); const [orderOpen, setOrderOpen] = useState(false); const [invoiceOpen, setInvoiceOpen] = useState(false); const [ledger, setLedger] = useState<any[] | null>(null); const [ledgerName, setLedgerName] = useState('');
  const { data: items = [] } = useQuery<Item[]>({ queryKey: ['commerce-items'], queryFn: async () => (await api.get('/commerce/items')).data });
  const { data: customers = [] } = useQuery<Customer[]>({ queryKey: ['commerce-customers'], queryFn: async () => (await api.get('/commerce/customers')).data });
  const { data: orders = [] } = useQuery<any[]>({ queryKey: ['commerce-orders'], queryFn: async () => (await api.get('/commerce/orders')).data });
  const { data: invoices = [] } = useQuery<any[]>({ queryKey: ['commerce-invoices'], queryFn: async () => (await api.get('/commerce/invoices')).data });
  const refresh = (keys: string[]) => Promise.all(keys.map(key => client.invalidateQueries({ queryKey: [key] })));
  const [item, setItem] = useState({ name: '', sku: '', type: 'YARN', uom: 'KG', hsnSac: '', gstRate: '5', salePrice: '', reorderLevel: '', imageUrl: '' });
  const [customer, setCustomer] = useState({ name: '', phone: '', gstin: '', state: 'Tamil Nadu', address: '' });
  const emptySales = () => ({ customerId: '' as number | '', date: new Date().toLocaleDateString('en-CA'), notes: '', sellerState: 'Tamil Nadu', lines: [{ itemId: '' as number | '', quantity: '', rate: '', discount: '' }] as Line[] });
  const [order, setOrder] = useState(emptySales); const [invoice, setInvoice] = useState({ ...emptySales(), dueDate: '', theme: 'CLASSIC', currency: 'INR', notes: '', terms: 'Payment due by the due date.', transportMode: '', vehicleNo: '', issuerSignature: '', salesOrderId: '' as number | '' });
  const saveItem = async () => { try { await api.post('/commerce/items', { ...item, gstRate: Number(item.gstRate), salePrice: Number(item.salePrice || 0), reorderLevel: Number(item.reorderLevel || 0) }); setItemOpen(false); setItem({ name: '', sku: '', type: 'YARN', uom: 'KG', hsnSac: '', gstRate: '5', salePrice: '', reorderLevel: '', imageUrl: '' }); await refresh(['commerce-items']); toast.success('Catalogue item created'); } catch (e: any) { toast.error(e.response?.data?.message || 'Could not create item'); } };
  const saveCustomer = async () => { try { await api.post('/commerce/customers', customer); setCustomerOpen(false); setCustomer({ name: '', phone: '', gstin: '', state: 'Tamil Nadu', address: '' }); await refresh(['commerce-customers']); toast.success('Customer created'); } catch (e: any) { toast.error(e.response?.data?.message || 'Could not create customer'); } };
  const submitOrder = async () => { try { await api.post('/commerce/orders', { ...order, lines: order.lines.map(line => ({ itemId: line.itemId, quantity: Number(line.quantity), rate: line.rate ? Number(line.rate) : undefined, discount: Number(line.discount || 0) })) }); setOrderOpen(false); setOrder(emptySales()); await refresh(['commerce-orders', 'commerce-items']); toast.success('Sales order created and stock reserved'); } catch (e: any) { toast.error(e.response?.data?.message || 'Could not create order'); } };
  const submitInvoice = async () => { try { await api.post('/commerce/invoices', { ...invoice, salesOrderId: invoice.salesOrderId || undefined, buyerState: customers.find(x => x.id === invoice.customerId)?.state, lines: invoice.lines.map(line => ({ itemId: line.itemId, quantity: Number(line.quantity), rate: line.rate ? Number(line.rate) : undefined, discount: Number(line.discount || 0) })) }); setInvoiceOpen(false); setInvoice({ ...emptySales(), dueDate: '', theme: 'CLASSIC', currency: 'INR', notes: '', terms: 'Payment due by the due date.', transportMode: '', vehicleNo: '', issuerSignature: '', salesOrderId: '' }); await refresh(['commerce-invoices', 'commerce-items', 'commerce-customers', 'commerce-orders']); toast.success('GST invoice finalised'); } catch (e: any) { toast.error(e.response?.data?.message || 'Could not finalise invoice'); } };
  const convertOrder = (selected: any) => { setInvoice({ ...emptySales(), customerId: selected.customerId, salesOrderId: selected.id, dueDate: '', theme: 'CLASSIC', currency: 'INR', notes: selected.notes || '', terms: 'Payment due by the due date.', transportMode: '', vehicleNo: '', issuerSignature: '', lines: selected.lines.filter((x: any) => x.quantity > x.invoicedQty).map((x: any) => ({ itemId: x.itemId, quantity: String(x.quantity - x.invoicedQty), rate: String(x.rate), discount: String(x.discount || 0) })) }); setInvoiceOpen(true); };
  const invoicePreview = useMemo(() => invoice.lines.reduce((sum, line) => { const found = items.find(x => x.id === line.itemId); const taxable = Number(line.quantity || 0) * Number(line.rate || found?.salePrice || 0) - Number(line.discount || 0); return sum + taxable * (1 + Number(found?.gstRate || 0) / 100); }, 0), [invoice.lines, items]);
  const lineEditor = (sales: typeof order, setSales: React.Dispatch<React.SetStateAction<any>>) => <><Stack spacing={1}>{sales.lines.map((line, index) => <Stack key={index} direction={{ xs: 'column', sm: 'row' }} spacing={1}><TextField select label="Item" value={line.itemId} onChange={e => setSales((old: any) => ({ ...old, lines: old.lines.map((entry: Line, i: number) => i === index ? { ...entry, itemId: Number(e.target.value) } : entry) }))} fullWidth>{items.map(x => <MenuItem key={x.id} value={x.id}>{x.name} · {x.stock.available} {x.uom}</MenuItem>)}</TextField><TextField label="Qty" type="number" value={line.quantity} onChange={e => setSales((old: any) => ({ ...old, lines: old.lines.map((entry: Line, i: number) => i === index ? { ...entry, quantity: e.target.value } : entry) }))} /><TextField label="Rate" type="number" value={line.rate} onChange={e => setSales((old: any) => ({ ...old, lines: old.lines.map((entry: Line, i: number) => i === index ? { ...entry, rate: e.target.value } : entry) }))} /><TextField label="Discount" type="number" value={line.discount} onChange={e => setSales((old: any) => ({ ...old, lines: old.lines.map((entry: Line, i: number) => i === index ? { ...entry, discount: e.target.value } : entry) }))} /></Stack>)}</Stack><Button onClick={() => setSales((old: any) => ({ ...old, lines: [...old.lines, { itemId: '', quantity: '', rate: '', discount: '' }] }))} sx={{ alignSelf: 'start' }}>+ Add line</Button></>;
  return <Box sx={{ maxWidth: 1250, mx: 'auto', width: '100%' }}><Box sx={{ display: 'flex', justifyContent: 'space-between', flexWrap: 'wrap', gap: 2, mb: 2 }}><Box><Typography variant="h4" fontWeight={800}>Business Desk</Typography><Typography color="text.secondary">Catalogue, customers, orders and GST invoices use one shared stock and ledger.</Typography></Box><Stack direction="row" spacing={1}><Button variant="outlined" startIcon={<CustomerIcon />} onClick={() => setCustomerOpen(true)}>Customer</Button><Button variant="outlined" startIcon={<OrderIcon />} onClick={() => setOrderOpen(true)}>Order</Button><Button variant="contained" startIcon={<InvoiceIcon />} onClick={() => setInvoiceOpen(true)}>Invoice Studio</Button></Stack></Box><Paper variant="outlined" sx={{ borderRadius: 3 }}><Tabs value={tab} onChange={(_, value) => setTab(value)} variant="scrollable"><Tab icon={<CatalogueIcon />} iconPosition="start" label="Catalogue" /><Tab icon={<CustomerIcon />} iconPosition="start" label="Customers & Ledger" /><Tab icon={<OrderIcon />} iconPosition="start" label="Sales Orders" /><Tab icon={<InvoiceIcon />} iconPosition="start" label="Invoices" /></Tabs></Paper>
    {tab === 0 && <Box sx={{ mt: 2 }}><Button startIcon={<AddIcon />} variant="contained" onClick={() => setItemOpen(true)} sx={{ mb: 2 }}>Add catalogue item</Button><TableContainer component={Paper} variant="outlined"><Table><TableHead><TableRow><TableCell>Item</TableCell><TableCell>Type</TableCell><TableCell>HSN / GST</TableCell><TableCell>Stock</TableCell><TableCell>Price</TableCell></TableRow></TableHead><TableBody>{items.map(x => <TableRow key={x.id}><TableCell><Typography fontWeight={700}>{x.name}</Typography><Typography variant="caption">{x.sku}</Typography></TableCell><TableCell>{x.type.replace('_', ' ')}</TableCell><TableCell>{x.hsnSac || '—'} · {x.gstRate}%</TableCell><TableCell sx={{ color: x.stock.available <= x.reorderLevel ? 'error.main' : 'inherit' }}>{x.stock.available} {x.uom}</TableCell><TableCell>₹{x.salePrice.toLocaleString('en-IN')}</TableCell></TableRow>)}{!items.length && <TableRow><TableCell colSpan={5} align="center" sx={{ py: 6 }}>No catalogue items yet.</TableCell></TableRow>}</TableBody></Table></TableContainer></Box>}
    {tab === 1 && <Box sx={{ mt: 2 }}><TableContainer component={Paper} variant="outlined"><Table><TableHead><TableRow><TableCell>Customer</TableCell><TableCell>Contact / GSTIN</TableCell><TableCell>State</TableCell><TableCell align="right">Balance</TableCell><TableCell /></TableRow></TableHead><TableBody>{customers.map(x => <TableRow key={x.id}><TableCell sx={{ fontWeight: 'bold' }}>{x.name}</TableCell><TableCell>{x.phone || '—'}<br />{x.gstin || ''}</TableCell><TableCell>{x.state}</TableCell><TableCell align="right" sx={{ color: x.balance > 0 ? 'error.main' : 'success.main' }}>₹{x.balance.toLocaleString('en-IN')}</TableCell><TableCell><Button size="small" onClick={async () => { setLedgerName(x.name); setLedger((await api.get(`/commerce/customers/${x.id}/ledger`)).data); }}>Ledger</Button></TableCell></TableRow>)}</TableBody></Table></TableContainer></Box>}
    {tab === 2 && <Box sx={{ mt: 2 }}><TableContainer component={Paper} variant="outlined"><Table><TableHead><TableRow><TableCell>Order</TableCell><TableCell>Customer</TableCell><TableCell>Status</TableCell><TableCell align="right">Total</TableCell><TableCell /></TableRow></TableHead><TableBody>{orders.map(x => <TableRow key={x.id}><TableCell>{x.orderNo}</TableCell><TableCell>{x.customer?.name}</TableCell><TableCell>{x.status}</TableCell><TableCell align="right">₹{x.total.toLocaleString('en-IN')}</TableCell><TableCell>{['CONFIRMED','PARTIALLY_INVOICED'].includes(x.status) && <Button size="small" onClick={() => convertOrder(x)}>Invoice</Button>}{x.status === 'CONFIRMED' && <Button size="small" color="error" onClick={async()=>{try{await api.post(`/commerce/orders/${x.id}/cancel`,{notes:'Cancelled from Business Desk'});await refresh(['commerce-orders','commerce-items']);toast.success('Order cancelled and stock released');}catch(e:any){toast.error(e.response?.data?.message||'Could not cancel order')}}}>Cancel</Button>}</TableCell></TableRow>)}</TableBody></Table></TableContainer></Box>}
    {tab === 3 && <Box sx={{ mt: 2 }}><TableContainer component={Paper} variant="outlined"><Table><TableHead><TableRow><TableCell>Invoice</TableCell><TableCell>Customer</TableCell><TableCell>GST</TableCell><TableCell>Status</TableCell><TableCell align="right">Total</TableCell><TableCell /></TableRow></TableHead><TableBody>{invoices.map(x => <TableRow key={x.id}><TableCell><Typography fontWeight={700}>{x.invoiceNo}</Typography><Typography variant="caption">{x.documentHash?.slice(0, 12)}</Typography></TableCell><TableCell>{x.customer?.name}</TableCell><TableCell>CGST ₹{x.cgst} · SGST ₹{x.sgst} · IGST ₹{x.igst}</TableCell><TableCell>{x.status}</TableCell><TableCell align="right">₹{x.total.toLocaleString('en-IN')}</TableCell><TableCell><Button size="small" onClick={()=>window.print()}>Print</Button>{!['PAID','VOID'].includes(x.status)&&<Button size="small" onClick={async()=>{const amount=window.prompt(`Payment amount (balance ₹${(x.total-x.amountPaid).toFixed(2)})`);if(!amount)return;try{await api.post(`/commerce/invoices/${x.id}/payments`,{amount:Number(amount),method:'CASH'});await refresh(['commerce-invoices','commerce-customers']);toast.success('Payment recorded')}catch(e:any){toast.error(e.response?.data?.message||'Could not record payment')}}}>Pay</Button>}{x.status!=='VOID'&&<Button size="small" color="error" onClick={async()=>{try{await api.post(`/commerce/invoices/${x.id}/void`,{notes:'Voided from Invoice Studio'});await refresh(['commerce-invoices','commerce-customers','commerce-items']);toast.success('Invoice voided')}catch(e:any){toast.error(e.response?.data?.message||'Could not void invoice')}}}>Void</Button>}</TableCell></TableRow>)}</TableBody></Table></TableContainer></Box>}
    <Dialog open={itemOpen} onClose={() => setItemOpen(false)} fullWidth maxWidth="sm"><DialogTitle>Add catalogue item</DialogTitle><DialogContent><Stack spacing={2} sx={{ pt: 1 }}><Stack direction="row" spacing={2}><TextField label="Name" value={item.name} onChange={e => setItem({ ...item, name: e.target.value })} fullWidth /><TextField label="SKU" value={item.sku} onChange={e => setItem({ ...item, sku: e.target.value })} fullWidth /></Stack><Stack direction="row" spacing={2}><TextField select label="Type" value={item.type} onChange={e => setItem({ ...item, type: e.target.value })} fullWidth>{['RAW_MATERIAL', 'YARN', 'FINISHED_GOOD', 'JOB_WORK_MATERIAL', 'SERVICE'].map(x => <MenuItem key={x} value={x}>{x.replace('_', ' ')}</MenuItem>)}</TextField><TextField label="UOM" value={item.uom} onChange={e => setItem({ ...item, uom: e.target.value })} /></Stack><Stack direction="row" spacing={2}><TextField label="HSN/SAC" value={item.hsnSac} onChange={e => setItem({ ...item, hsnSac: e.target.value })} /><TextField label="GST %" type="number" value={item.gstRate} onChange={e => setItem({ ...item, gstRate: e.target.value })} /><TextField label="Sale price" type="number" value={item.salePrice} onChange={e => setItem({ ...item, salePrice: e.target.value })} /></Stack><TextField label="Low-stock threshold" type="number" value={item.reorderLevel} onChange={e => setItem({ ...item, reorderLevel: e.target.value })} /><TextField label="Product image URL" value={item.imageUrl} onChange={e => setItem({ ...item, imageUrl: e.target.value })} helperText="Optional image reference stored with this catalogue item." /></Stack></DialogContent><DialogActions><Button onClick={() => setItemOpen(false)}>Cancel</Button><Button variant="contained" onClick={saveItem}>Save</Button></DialogActions></Dialog>
    <Dialog open={customerOpen} onClose={() => setCustomerOpen(false)} fullWidth maxWidth="sm"><DialogTitle>Add customer</DialogTitle><DialogContent><Stack spacing={2} sx={{ pt: 1 }}><TextField label="Name" value={customer.name} onChange={e => setCustomer({ ...customer, name: e.target.value })} /><TextField label="Phone" value={customer.phone} onChange={e => setCustomer({ ...customer, phone: e.target.value })} /><TextField label="GSTIN" value={customer.gstin} onChange={e => setCustomer({ ...customer, gstin: e.target.value })} /><TextField select label="State" value={customer.state} onChange={e => setCustomer({ ...customer, state: e.target.value })}>{stateNames.map(x => <MenuItem key={x} value={x}>{x}</MenuItem>)}</TextField><TextField label="Address" value={customer.address} onChange={e => setCustomer({ ...customer, address: e.target.value })} multiline /></Stack></DialogContent><DialogActions><Button onClick={() => setCustomerOpen(false)}>Cancel</Button><Button variant="contained" onClick={saveCustomer}>Save</Button></DialogActions></Dialog>
    <Dialog open={orderOpen} onClose={() => setOrderOpen(false)} fullWidth maxWidth="md"><DialogTitle>New sales order</DialogTitle><DialogContent><Stack spacing={2} sx={{ pt: 1 }}><TextField select label="Customer" value={order.customerId} onChange={e => setOrder({ ...order, customerId: Number(e.target.value) })}>{customers.map(x => <MenuItem key={x.id} value={x.id}>{x.name}</MenuItem>)}</TextField>{lineEditor(order, setOrder)}<TextField label="Notes" value={order.notes} onChange={e => setOrder({ ...order, notes: e.target.value })} /></Stack></DialogContent><DialogActions><Button onClick={() => setOrderOpen(false)}>Cancel</Button><Button variant="contained" onClick={submitOrder}>Reserve stock</Button></DialogActions></Dialog>
    <Dialog open={invoiceOpen} onClose={() => setInvoiceOpen(false)} fullWidth maxWidth="md"><DialogTitle>Invoice Studio</DialogTitle><DialogContent><Stack spacing={2} sx={{ pt: 1 }}><Stack direction={{ xs: 'column', sm: 'row' }} spacing={2}><TextField select label="Customer" value={invoice.customerId} onChange={e => setInvoice({ ...invoice, customerId: Number(e.target.value) })} fullWidth>{customers.map(x => <MenuItem key={x.id} value={x.id}>{x.name}</MenuItem>)}</TextField><TextField select label="Seller state" value={invoice.sellerState} onChange={e => setInvoice({ ...invoice, sellerState: e.target.value })} fullWidth>{stateNames.map(x => <MenuItem key={x} value={x}>{x}</MenuItem>)}</TextField><TextField label="Due date" type="date" value={invoice.dueDate} onChange={e => setInvoice({ ...invoice, dueDate: e.target.value })} InputLabelProps={{ shrink: true }} /></Stack>{lineEditor(invoice, setInvoice)}<Stack direction={{xs:'column',sm:'row'}} spacing={1}><TextField select label="Template" value={invoice.theme} onChange={e=>setInvoice({...invoice,theme:e.target.value})}>{['CLASSIC','MODERN','MINIMAL'].map(x=><MenuItem value={x} key={x}>{x}</MenuItem>)}</TextField><TextField label="Transport mode" value={invoice.transportMode} onChange={e=>setInvoice({...invoice,transportMode:e.target.value})}/><TextField label="Vehicle number" value={invoice.vehicleNo} onChange={e=>setInvoice({...invoice,vehicleNo:e.target.value})}/><TextField label="Authorised signatory" value={invoice.issuerSignature} onChange={e=>setInvoice({...invoice,issuerSignature:e.target.value})}/></Stack><TextField label="Notes" value={invoice.notes} onChange={e=>setInvoice({...invoice,notes:e.target.value})} multiline/><TextField label="Terms" value={invoice.terms} onChange={e=>setInvoice({...invoice,terms:e.target.value})} multiline/><Paper variant="outlined" sx={{ p: 2 }}><Typography fontWeight={800}>Live GST total: ₹{invoicePreview.toLocaleString('en-IN', { maximumFractionDigits: 2 })}</Typography><Typography variant="caption" color="text.secondary">Rule checks: confirm HSN/SAC and GST for each item, set a due date, then finalise. Intra-state invoices split CGST/SGST; interstate invoices use IGST and receive a SHA-256 verification fingerprint.</Typography></Paper></Stack></DialogContent><DialogActions><Button onClick={() => setInvoiceOpen(false)}>Cancel</Button><Button variant="contained" onClick={submitInvoice}>Finalise invoice</Button></DialogActions></Dialog>
    <Dialog open={!!ledger} onClose={() => setLedger(null)} fullWidth maxWidth="sm"><DialogTitle>{ledgerName} ledger</DialogTitle><DialogContent><Table><TableHead><TableRow><TableCell>Date</TableCell><TableCell>Type</TableCell><TableCell align="right">Debit</TableCell><TableCell align="right">Credit</TableCell></TableRow></TableHead><TableBody>{ledger?.map(row => <TableRow key={row.id}><TableCell>{new Date(row.date).toLocaleDateString('en-IN')}</TableCell><TableCell>{row.type}</TableCell><TableCell align="right">₹{row.debit}</TableCell><TableCell align="right">₹{row.credit}</TableCell></TableRow>)}</TableBody></Table></DialogContent><DialogActions><Button onClick={() => setLedger(null)}>Close</Button></DialogActions></Dialog>
  </Box>;
};
export default CommerceDesk;
