import React, { useMemo, useState } from 'react';
import { Add as AddIcon, AssignmentTurnedIn as ReceiptIcon, LocalShipping as DispatchIcon, PersonAdd as WorkerIcon } from '@mui/icons-material';
import { Box, Button, Chip, Dialog, DialogActions, DialogContent, DialogTitle, Grid, MenuItem, Paper, Stack, Table, TableBody, TableCell, TableContainer, TableHead, TableRow, TextField, Typography } from '@mui/material';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { toast } from 'sonner';
import api from '../utils/api';

type Item = { id: number; name: string; uom: string; type: string; stock?: { available: number } };
type Worker = { id: number; name: string };
type Line = { itemId: number | ''; quantity: string; scrapQty?: string };
type Job = { id: number; challanNo: string; date: string; processType: string; status: string; jobWorker: Worker; dispatchLines: Array<{ item: Item; quantity: number }>; receiptLines: Array<{ item: Item; quantity: number; scrapQty: number }> };
const colors: Record<string, 'warning' | 'info' | 'success'> = { DISPATCHED: 'warning', PART_RECEIVED: 'info', COMPLETED: 'success' };

const JobWork: React.FC = () => {
  const client = useQueryClient(); const [open, setOpen] = useState(false); const [workerOpen, setWorkerOpen] = useState(false); const [receipt, setReceipt] = useState<Job | null>(null); const [workerName, setWorkerName] = useState('');
  const [form, setForm] = useState({ jobWorkerId: '' as number | '', processType: 'DYEING', date: new Date().toLocaleDateString('en-CA'), notes: '', lines: [{ itemId: '' as number | '', quantity: '' }] as Line[] });
  const [receiptLines, setReceiptLines] = useState<Line[]>([]);
  const { data: items = [] } = useQuery<Item[]>({ queryKey: ['commerce-items'], queryFn: async () => (await api.get('/commerce/items')).data });
  const { data: workers = [] } = useQuery<Worker[]>({ queryKey: ['job-workers'], queryFn: async () => (await api.get('/job-work/workers')).data });
  const { data: jobs = [], isLoading } = useQuery<Job[]>({ queryKey: ['job-work'], queryFn: async () => (await api.get('/job-work')).data });
  const { data: summary = { openJobs: 0, completedJobs: 0, outstandingQty: 0 } } = useQuery({ queryKey: ['job-work-summary'], queryFn: async () => (await api.get('/job-work/summary')).data });
  const refresh = async () => { await Promise.all(['job-work', 'job-work-summary', 'commerce-items'].map(key => client.invalidateQueries({ queryKey: [key] }))); };
  const materials = items.filter(item => item.type !== 'SERVICE');
  const createWorker = async () => { try { if (!workerName.trim()) return toast.error('Worker name is required'); const { data } = await api.post('/job-work/workers', { name: workerName }); setForm({ ...form, jobWorkerId: data.id }); setWorkerName(''); setWorkerOpen(false); await client.invalidateQueries({ queryKey: ['job-workers'] }); } catch (error: any) { toast.error(error.response?.data?.message || 'Could not add worker'); } };
  const dispatch = async () => { try { await api.post('/job-work/dispatch', { ...form, lines: form.lines.map(line => ({ ...line, quantity: Number(line.quantity) })) }); setOpen(false); await refresh(); toast.success('Job-work challan dispatched'); } catch (error: any) { toast.error(error.response?.data?.message || 'Could not dispatch material'); } };
  const openReceipt = (job: Job) => { setReceipt(job); setReceiptLines(job.dispatchLines.map(line => ({ itemId: line.item.id, quantity: '', scrapQty: '' }))); };
  const saveReceipt = async () => { try { if (!receipt) return; const lines = receiptLines.filter(line => Number(line.quantity) || Number(line.scrapQty)).map(line => ({ ...line, quantity: Number(line.quantity || 0), scrapQty: Number(line.scrapQty || 0) })); await api.post(`/job-work/${receipt.id}/receive`, { lines }); setReceipt(null); await refresh(); toast.success('Job-work receipt recorded'); } catch (error: any) { toast.error(error.response?.data?.message || 'Could not record receipt'); } };
  const stats = useMemo(() => [['Open challans', summary.openJobs, <DispatchIcon />], ['With processors', `${Number(summary.outstandingQty || 0).toLocaleString('en-IN')} kg`, <DispatchIcon />], ['Completed', summary.completedJobs, <ReceiptIcon />]], [summary]);
  return <Box sx={{ maxWidth: 1200, mx: 'auto', width: '100%' }}>
    <Box sx={{ display: 'flex', flexWrap: 'wrap', justifyContent: 'space-between', gap: 2, mb: 3 }}><Box><Typography variant="h4" fontWeight={800}>Job Work</Typography><Typography color="text.secondary">Persistent challans, processor receipts, scrap and stock movements.</Typography></Box><Stack direction="row" spacing={1}><Button variant="outlined" startIcon={<WorkerIcon />} onClick={() => setWorkerOpen(true)}>Add worker</Button><Button variant="contained" startIcon={<AddIcon />} onClick={() => setOpen(true)}>New dispatch</Button></Stack></Box>
    <Grid container spacing={2.5} sx={{ mb: 3 }}>{stats.map(([label, value, icon]) => <Grid key={String(label)} size={{ xs: 12, sm: 4 }}><Paper variant="outlined" sx={{ p: 2.5, borderRadius: 3, display: 'flex', gap: 2, alignItems: 'center' }}><Box sx={{ bgcolor: 'primary.light', color: 'primary.dark', p: 1, borderRadius: 2 }}>{icon}</Box><Box><Typography variant="body2" color="text.secondary">{label}</Typography><Typography variant="h5" fontWeight={800}>{value}</Typography></Box></Paper></Grid>)}</Grid>
    <TableContainer component={Paper} variant="outlined" sx={{ borderRadius: 3 }}><Table><TableHead><TableRow><TableCell>Challan</TableCell><TableCell>Worker</TableCell><TableCell>Process</TableCell><TableCell>Materials</TableCell><TableCell>Status</TableCell><TableCell /></TableRow></TableHead><TableBody>{isLoading ? <TableRow><TableCell colSpan={6}>Loading…</TableCell></TableRow> : jobs.length === 0 ? <TableRow><TableCell colSpan={6} align="center" sx={{ py: 7 }}>No job-work challans yet.</TableCell></TableRow> : jobs.map(job => <TableRow key={job.id} hover><TableCell><Typography fontWeight={700}>{job.challanNo}</Typography><Typography variant="caption">{new Date(job.date).toLocaleDateString('en-IN')}</Typography></TableCell><TableCell>{job.jobWorker.name}</TableCell><TableCell>{job.processType}</TableCell><TableCell>{job.dispatchLines.map(line => `${line.item.name} · ${line.quantity} ${line.item.uom}`).join(', ')}</TableCell><TableCell><Chip size="small" color={colors[job.status] || 'warning'} label={job.status.replace('_', ' ')} /></TableCell><TableCell>{job.status !== 'COMPLETED' && <Button size="small" startIcon={<ReceiptIcon />} onClick={() => openReceipt(job)}>Receive</Button>}</TableCell></TableRow>)}</TableBody></Table></TableContainer>
    <Dialog open={open} onClose={() => setOpen(false)} fullWidth maxWidth="md"><DialogTitle>Dispatch material for job work</DialogTitle><DialogContent><Stack spacing={2} sx={{ pt: 1 }}><Stack direction={{ xs: 'column', sm: 'row' }} spacing={2}><TextField select label="Job worker" value={form.jobWorkerId} onChange={e => setForm({ ...form, jobWorkerId: Number(e.target.value) })} fullWidth>{workers.map(worker => <MenuItem key={worker.id} value={worker.id}>{worker.name}</MenuItem>)}</TextField><TextField select label="Process" value={form.processType} onChange={e => setForm({ ...form, processType: e.target.value })} fullWidth>{['KNITTING', 'DYEING', 'PRINTING', 'STITCHING', 'WINDING'].map(value => <MenuItem key={value} value={value}>{value}</MenuItem>)}</TextField></Stack>{form.lines.map((line, index) => <Stack key={index} direction="row" spacing={1}><TextField select label="Material" value={line.itemId} onChange={e => setForm({ ...form, lines: form.lines.map((entry, i) => i === index ? { ...entry, itemId: Number(e.target.value) } : entry) })} fullWidth>{materials.map(item => <MenuItem key={item.id} value={item.id}>{item.name} ({item.stock?.available ?? 0} {item.uom})</MenuItem>)}</TextField><TextField label="Qty" type="number" value={line.quantity} onChange={e => setForm({ ...form, lines: form.lines.map((entry, i) => i === index ? { ...entry, quantity: e.target.value } : entry) })} sx={{ maxWidth: 180 }} /></Stack>)}<Button onClick={() => setForm({ ...form, lines: [...form.lines, { itemId: '', quantity: '' }] })} sx={{ alignSelf: 'start' }}>+ Add material</Button><TextField label="Notes" value={form.notes} onChange={e => setForm({ ...form, notes: e.target.value })} /></Stack></DialogContent><DialogActions><Button onClick={() => setOpen(false)}>Cancel</Button><Button variant="contained" onClick={dispatch}>Dispatch</Button></DialogActions></Dialog>
    <Dialog open={!!receipt} onClose={() => setReceipt(null)} fullWidth maxWidth="sm"><DialogTitle>Receive from {receipt?.challanNo}</DialogTitle><DialogContent><Stack spacing={2} sx={{ pt: 1 }}>{receiptLines.map((line, index) => <Stack key={String(line.itemId)} direction="row" spacing={1}><TextField disabled value={items.find(item => item.id === line.itemId)?.name || ''} fullWidth /><TextField label="Received" type="number" value={line.quantity} onChange={e => setReceiptLines(receiptLines.map((entry, i) => i === index ? { ...entry, quantity: e.target.value } : entry))} /><TextField label="Scrap" type="number" value={line.scrapQty} onChange={e => setReceiptLines(receiptLines.map((entry, i) => i === index ? { ...entry, scrapQty: e.target.value } : entry))} /></Stack>)}</Stack></DialogContent><DialogActions><Button onClick={() => setReceipt(null)}>Cancel</Button><Button variant="contained" onClick={saveReceipt}>Record receipt</Button></DialogActions></Dialog>
    <Dialog open={workerOpen} onClose={() => setWorkerOpen(false)}><DialogTitle>Add job worker</DialogTitle><DialogContent><TextField autoFocus fullWidth sx={{ mt: 1 }} label="Worker name" value={workerName} onChange={e => setWorkerName(e.target.value)} /></DialogContent><DialogActions><Button onClick={() => setWorkerOpen(false)}>Cancel</Button><Button variant="contained" onClick={createWorker}>Save</Button></DialogActions></Dialog>
  </Box>;
};
export default JobWork;
