import React, { useMemo, useState } from 'react';
import { Add, History, LocalShipping, Print } from '@mui/icons-material';
import { Box, Button, Dialog, DialogActions, DialogContent, DialogTitle, MenuItem, Paper, Stack, Tab, Tabs, Table, TableBody, TableCell, TableHead, TableRow, TextField, Typography } from '@mui/material';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { toast } from 'sonner';
import api from '../utils/api';

type Item = { id:number; name:string; sku:string; uom:string; stock:{available:number} };
type Row = { itemId:number | ''; quantity:string; unitCost:string };
const newRow = (): Row => ({ itemId:'', quantity:'', unitCost:'' });

const OperationsDesk: React.FC = () => {
  const client = useQueryClient(); const [tab,setTab]=useState(0); const [inwardOpen,setInwardOpen]=useState(false); const [costOpen,setCostOpen]=useState(false); const [history,setHistory]=useState<any[]|null>(null); const [historyName,setHistoryName]=useState('');
  const { data: items=[] }=useQuery<Item[]>({queryKey:['commerce-items'],queryFn:async()=> (await api.get('/commerce/items')).data});
  const { data: receipts=[] }=useQuery<any[]>({queryKey:['inward-receipts'],queryFn:async()=> (await api.get('/commerce/inward-receipts')).data});
  const { data: costings=[] }=useQuery<any[]>({queryKey:['costing-sheets'],queryFn:async()=> (await api.get('/commerce/costing-sheets')).data});
  const [inward,setInward]=useState({supplierName:'',referenceNumber:'',date:new Date().toLocaleDateString('en-CA'),notes:'',lines:[newRow()]});
  const [costing,setCosting]=useState({styleCode:'',description:'',components:[{type:'MATERIAL',description:'',quantity:'',rate:''}]});
  const total=useMemo(()=>inward.lines.reduce((s,l)=>s+Number(l.quantity||0)*Number(l.unitCost||0),0),[inward]);
  const costTotal=useMemo(()=>costing.components.reduce((s,l)=>s+Number(l.quantity||0)*Number(l.rate||0),0),[costing]);
  const refresh=()=>Promise.all(['commerce-items','inward-receipts','costing-sheets'].map(key=>client.invalidateQueries({queryKey:[key]})));
  const saveInward=async()=>{try{await api.post('/commerce/inward-receipts',{...inward,lines:inward.lines.map(x=>({...x,quantity:Number(x.quantity),unitCost:Number(x.unitCost)}))});setInwardOpen(false);setInward({supplierName:'',referenceNumber:'',date:new Date().toLocaleDateString('en-CA'),notes:'',lines:[newRow()]});await refresh();toast.success('Inward receipt posted to stock');}catch(e:any){toast.error(e.response?.data?.message||'Could not save receipt');}};
  const saveCost=async()=>{try{await api.post('/commerce/costing-sheets',{...costing,components:costing.components.map(x=>({...x,quantity:Number(x.quantity),rate:Number(x.rate)}))});setCostOpen(false);setCosting({styleCode:'',description:'',components:[{type:'MATERIAL',description:'',quantity:'',rate:''}]});await refresh();toast.success('Costing sheet saved');}catch(e:any){toast.error(e.response?.data?.message||'Could not save costing');}};
  const print=()=>window.print();
  return <Box sx={{maxWidth:1200,mx:'auto',width:'100%'}}><Box sx={{display:'flex',justifyContent:'space-between',flexWrap:'wrap',gap:2,mb:2}}><Box><Typography variant="h4" fontWeight={800}>Operations Desk</Typography><Typography color="text.secondary">Supplier receipts, garment costing and a traceable stock ledger.</Typography></Box><Stack direction="row" spacing={1}><Button variant="outlined" startIcon={<LocalShipping/>} onClick={()=>setInwardOpen(true)}>Receive stock</Button><Button variant="contained" startIcon={<Add/>} onClick={()=>setCostOpen(true)}>Costing sheet</Button></Stack></Box><Paper variant="outlined" sx={{borderRadius:3}}><Tabs value={tab} onChange={(_,v)=>setTab(v)}><Tab label="Inward receipts"/><Tab label="Costing history"/><Tab label="Stock history"/></Tabs></Paper>
  {tab===0&&<Table component={Paper} sx={{mt:2}}><TableHead><TableRow><TableCell>Receipt</TableCell><TableCell>Supplier</TableCell><TableCell>Date</TableCell><TableCell align="right">Value</TableCell><TableCell/></TableRow></TableHead><TableBody>{receipts.map(r=><TableRow key={r.id}><TableCell>{r.receiptNo}</TableCell><TableCell>{r.supplierName}</TableCell><TableCell>{new Date(r.date).toLocaleDateString('en-IN')}</TableCell><TableCell align="right">₹{Number(r.total).toLocaleString('en-IN')}</TableCell><TableCell><Button size="small" startIcon={<Print/>} onClick={print}>Print</Button></TableCell></TableRow>)}</TableBody></Table>}
  {tab===1&&<Table component={Paper} sx={{mt:2}}><TableHead><TableRow><TableCell>Style</TableCell><TableCell>Description</TableCell><TableCell>Status</TableCell><TableCell align="right">Cost</TableCell><TableCell/></TableRow></TableHead><TableBody>{costings.map(c=><TableRow key={c.id}><TableCell>{c.styleCode}</TableCell><TableCell>{c.description||'—'}</TableCell><TableCell>{c.status}</TableCell><TableCell align="right">₹{Number(c.total).toLocaleString('en-IN')}</TableCell><TableCell><Button size="small" onClick={()=>{setCosting({styleCode:c.styleCode,description:c.description||'',components:JSON.parse(c.components).map((x:any)=>({...x,quantity:String(x.quantity||x.qty||''),rate:String(x.rate||'')}))});setCostOpen(true);}}>Copy</Button></TableCell></TableRow>)}</TableBody></Table>}
  {tab===2&&<Table component={Paper} sx={{mt:2}}><TableHead><TableRow><TableCell>Item</TableCell><TableCell>Available</TableCell><TableCell/></TableRow></TableHead><TableBody>{items.map(i=><TableRow key={i.id}><TableCell>{i.name}<Typography variant="caption" display="block">{i.sku}</Typography></TableCell><TableCell>{i.stock.available} {i.uom}</TableCell><TableCell><Button startIcon={<History/>} size="small" onClick={async()=>{setHistoryName(i.name);setHistory((await api.get(`/commerce/items/${i.id}/movements`)).data)}}>History</Button></TableCell></TableRow>)}</TableBody></Table>}
  <Dialog open={inwardOpen} onClose={()=>setInwardOpen(false)} fullWidth maxWidth="md"><DialogTitle>Receive stock</DialogTitle><DialogContent><Stack spacing={2} sx={{pt:1}}><Stack direction={{xs:'column',sm:'row'}} spacing={1}><TextField label="Supplier" value={inward.supplierName} onChange={e=>setInward({...inward,supplierName:e.target.value})} fullWidth/><TextField label="Reference / PO" value={inward.referenceNumber} onChange={e=>setInward({...inward,referenceNumber:e.target.value})} fullWidth/><TextField type="date" label="Date" InputLabelProps={{shrink:true}} value={inward.date} onChange={e=>setInward({...inward,date:e.target.value})}/></Stack>{inward.lines.map((line,index)=><Stack key={index} direction={{xs:'column',sm:'row'}} spacing={1}><TextField select label="Item" value={line.itemId} onChange={e=>setInward({...inward,lines:inward.lines.map((x,i)=>i===index?{...x,itemId:Number(e.target.value)}:x)})} fullWidth>{items.map(i=><MenuItem value={i.id} key={i.id}>{i.name}</MenuItem>)}</TextField><TextField label="Quantity" type="number" value={line.quantity} onChange={e=>setInward({...inward,lines:inward.lines.map((x,i)=>i===index?{...x,quantity:e.target.value}:x)})}/><TextField label="Unit cost" type="number" value={line.unitCost} onChange={e=>setInward({...inward,lines:inward.lines.map((x,i)=>i===index?{...x,unitCost:e.target.value}:x)})}/></Stack>)}<Button onClick={()=>setInward({...inward,lines:[...inward.lines,newRow()]})}>+ Add item</Button><Typography fontWeight={800}>Receipt total: ₹{total.toLocaleString('en-IN')}</Typography></Stack></DialogContent><DialogActions><Button onClick={()=>setInwardOpen(false)}>Cancel</Button><Button variant="contained" onClick={saveInward}>Post receipt</Button></DialogActions></Dialog>
  <Dialog open={costOpen} onClose={()=>setCostOpen(false)} fullWidth maxWidth="md"><DialogTitle>Garment costing sheet</DialogTitle><DialogContent><Stack spacing={2} sx={{pt:1}}><Stack direction={{xs:'column',sm:'row'}} spacing={1}><TextField label="Style code" value={costing.styleCode} onChange={e=>setCosting({...costing,styleCode:e.target.value})} fullWidth/><TextField label="Description" value={costing.description} onChange={e=>setCosting({...costing,description:e.target.value})} fullWidth/></Stack>{costing.components.map((line,index)=><Stack key={index} direction={{xs:'column',sm:'row'}} spacing={1}><TextField select label="Type" value={line.type} onChange={e=>setCosting({...costing,components:costing.components.map((x,i)=>i===index?{...x,type:e.target.value}:x)})}>{['MATERIAL','PROCESS','OVERHEAD'].map(x=><MenuItem key={x} value={x}>{x}</MenuItem>)}</TextField><TextField label="Description" value={line.description} onChange={e=>setCosting({...costing,components:costing.components.map((x,i)=>i===index?{...x,description:e.target.value}:x)})} fullWidth/><TextField label="Qty" type="number" value={line.quantity} onChange={e=>setCosting({...costing,components:costing.components.map((x,i)=>i===index?{...x,quantity:e.target.value}:x)})}/><TextField label="Rate" type="number" value={line.rate} onChange={e=>setCosting({...costing,components:costing.components.map((x,i)=>i===index?{...x,rate:e.target.value}:x)})}/></Stack>)}<Button onClick={()=>setCosting({...costing,components:[...costing.components,{type:'MATERIAL',description:'',quantity:'',rate:''}]})}>+ Add component</Button><Typography fontWeight={800}>Total estimated cost: ₹{costTotal.toLocaleString('en-IN')}</Typography></Stack></DialogContent><DialogActions><Button onClick={()=>setCostOpen(false)}>Cancel</Button><Button variant="contained" onClick={saveCost}>Save sheet</Button></DialogActions></Dialog>
  <Dialog open={!!history} onClose={()=>setHistory(null)} fullWidth maxWidth="sm"><DialogTitle>{historyName} stock history</DialogTitle><DialogContent><Table><TableHead><TableRow><TableCell>Date</TableCell><TableCell>Movement</TableCell><TableCell align="right">Quantity</TableCell></TableRow></TableHead><TableBody>{history?.map(r=><TableRow key={r.id}><TableCell>{new Date(r.date).toLocaleDateString('en-IN')}</TableCell><TableCell>{r.movementType}</TableCell><TableCell align="right">{r.quantity}</TableCell></TableRow>)}</TableBody></Table></DialogContent><DialogActions><Button onClick={()=>setHistory(null)}>Close</Button></DialogActions></Dialog></Box>;
};
export default OperationsDesk;
