import { useMemo, useState } from 'react';
import { Box, Button, Chip, Container, Dialog, DialogContent, DialogTitle, Divider, Grid, IconButton, MenuItem, Paper, Stack, TextField, Typography } from '@mui/material';
import { Add, ArrowBack, CheckCircle, Close, Inventory2, LocalShipping, Remove, Search, ShoppingBag, ShoppingCart } from '@mui/icons-material';
import { useQuery } from '@tanstack/react-query';

type Product = { id: number; sku: string; name: string; description?: string; type: string; uom: string; gstRate: number; salePrice: number; brand?: string; category?: string; available: number | null; imageUrl?: string | null };
type CartLine = { itemId: number; quantity: number };
type Checkout = { name: string; phone: string; email: string; address: string; state: string; gstin: string; notes: string; website: string };
type OrderResult = { orderNo: string; subtotal: number; estimatedTax: number; estimatedTotal: number; status: string };

const initialCheckout: Checkout = { name: '', phone: '', email: '', address: '', state: 'Tamil Nadu', gstin: '', notes: '', website: '' };
const states = ['Tamil Nadu', 'Karnataka', 'Kerala', 'Andhra Pradesh', 'Telangana', 'Maharashtra', 'Gujarat', 'Delhi', 'Other'];
const money = (value: number) => `₹${value.toLocaleString('en-IN', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;

const words = {
  en: { shop: 'Shop', tagline: 'Textile products • India', collection: 'EVERGREEN ONE · WEAVE COLLECTION', hero: 'Textiles for every idea.', intro: 'Explore published yarn, finished goods and textile services. Stock and prices come directly from EverGreen.', sort: 'Sort', loadError: 'Products could not be loaded.', retry: 'Try again', paymentNotice: 'Orders are confirmed by our team. No online payment is collected.', sku: 'SKU', search: 'Search yarn, fabric and products', all: 'All categories', allBrands: 'All brands', newest: 'Name', priceLow: 'Price: low to high', priceHigh: 'Price: high to low', add: 'Add to cart', cart: 'Your cart', empty: 'Your cart is empty', noProducts: 'No products are published yet. Please check back soon.', noMatch: 'No products match these filters.', available: 'available', service: 'Service', gst: 'GST', subtotal: 'Subtotal', estimatedTax: 'Estimated GST', estimatedTotal: 'Estimated total', checkout: 'Continue to checkout', details: 'Delivery & contact details', name: 'Full name', phone: 'Phone number', email: 'Email (optional)', address: 'Delivery address', state: 'State', gstin: 'GSTIN (optional)', notes: 'Order notes (optional)', place: 'Place order', placing: 'Placing order…', success: 'Order request received', successNote: 'Your order has reserved stock. Our team will contact you about fulfilment and payment. No online payment was taken.', orderNo: 'Order number', back: 'Back to shop', view: 'View details', close: 'Close', unavailable: 'Out of stock', staff: 'Staff login' },
  ta: { shop: 'கடை', tagline: 'ஜவுளிப் பொருட்கள் • இந்தியா', collection: 'எவர்கிரீன் ஒன் · வீவ் தொகுப்பு', hero: 'ஒவ்வொரு யோசனைக்கும் ஜவுளி.', intro: 'வெளியிடப்பட்ட நூல், தயாரான பொருட்கள் மற்றும் ஜவுளிச் சேவைகளைப் பாருங்கள். இருப்பும் விலையும் எவர்கிரீனிலிருந்து நேரடியாக வருகிறது.', sort: 'வரிசை', loadError: 'பொருட்களை ஏற்ற முடியவில்லை.', retry: 'மீண்டும் முயற்சி', paymentNotice: 'ஆணைகளை எங்கள் குழு உறுதிப்படுத்தும். ஆன்லைன் கட்டணம் பெறப்படாது.', sku: 'பொருள் குறியீடு', search: 'நூல், துணி, பொருட்கள் தேடுங்கள்', all: 'அனைத்து வகைகள்', allBrands: 'அனைத்து பிராண்டுகள்', newest: 'பெயர்', priceLow: 'விலை: குறைவிலிருந்து', priceHigh: 'விலை: அதிகத்திலிருந்து', add: 'கூடையில் சேர்', cart: 'உங்கள் கூடை', empty: 'கூடை காலியாக உள்ளது', noProducts: 'இன்னும் பொருட்கள் வெளியிடப்படவில்லை. விரைவில் மீண்டும் பார்க்கவும்.', noMatch: 'இந்தத் தேடலுக்கு பொருட்கள் இல்லை.', available: 'கையிருப்பு', service: 'சேவை', gst: 'ஜிஎஸ்டி', subtotal: 'அடிப்படைத் தொகை', estimatedTax: 'மதிப்பிடப்பட்ட ஜிஎஸ்டி', estimatedTotal: 'மதிப்பிடப்பட்ட மொத்தம்', checkout: 'விவரங்களைத் தொடரவும்', details: 'விநியோகம் மற்றும் தொடர்பு', name: 'முழுப் பெயர்', phone: 'தொலைபேசி எண்', email: 'மின்னஞ்சல் (விருப்பம்)', address: 'விநியோக முகவரி', state: 'மாநிலம்', gstin: 'ஜிஎஸ்டிஐஎன் (விருப்பம்)', notes: 'ஆணை குறிப்பு (விருப்பம்)', place: 'ஆணையை இடு', placing: 'ஆணை சமர்ப்பிக்கப்படுகிறது…', success: 'ஆணை கோரிக்கை பெறப்பட்டது', successNote: 'உங்கள் ஆணைக்கான சரக்கு ஒதுக்கப்பட்டுள்ளது. விநியோகம் மற்றும் கட்டணம் குறித்து எங்கள் குழு தொடர்பு கொள்ளும். ஆன்லைன் கட்டணம் எடுக்கப்படவில்லை.', orderNo: 'ஆணை எண்', back: 'கடைக்குத் திரும்பு', view: 'விவரம்', close: 'மூடு', unavailable: 'கையிருப்பு இல்லை', staff: 'ஊழியர் நுழைவு' },
};

export default function ShopPortal() {
  const [language, setLanguage] = useState<'en' | 'ta'>(() => localStorage.getItem('shop-language') === 'ta' ? 'ta' : 'en');
  const t = words[language];
  const [search, setSearch] = useState('');
  const [category, setCategory] = useState('');
  const [brand, setBrand] = useState('');
  const [sort, setSort] = useState('name');
  const [cart, setCart] = useState<CartLine[]>([]);
  const [checkoutOpen, setCheckoutOpen] = useState(false);
  const [selected, setSelected] = useState<Product | null>(null);
  const [buyer, setBuyer] = useState<Checkout>(initialCheckout);
  const [submitting, setSubmitting] = useState(false);
  const [error, setError] = useState('');
  const [result, setResult] = useState<OrderResult | null>(null);
  const { data: products = [], isLoading, isError, refetch } = useQuery<Product[]>({ queryKey: ['storefront-products'], queryFn: async () => {
    const response = await fetch('/api/backend/storefront/products');
    if (!response.ok) throw new Error('Could not load products');
    return response.json();
  }, refetchOnWindowFocus: true, staleTime: 30_000 });
  const categories = useMemo(() => [...new Set(products.map(product => product.category).filter(Boolean))] as string[], [products]);
  const brands = useMemo(() => [...new Set(products.map(product => product.brand).filter(Boolean))] as string[], [products]);
  const filtered = useMemo(() => products.filter(product => {
    const matchesText = `${product.name} ${product.sku} ${product.description || ''}`.toLowerCase().includes(search.toLowerCase());
    return matchesText && (!category || product.category === category) && (!brand || product.brand === brand);
  }).sort((a, b) => sort === 'low' ? a.salePrice - b.salePrice : sort === 'high' ? b.salePrice - a.salePrice : a.name.localeCompare(b.name)), [products, search, category, brand, sort]);
  const cartRows = useMemo(() => cart.map(line => ({ ...line, product: products.find(product => product.id === line.itemId) })).filter(row => !!row.product), [cart, products]);
  const subtotal = cartRows.reduce((total, row) => total + row.quantity * row.product!.salePrice, 0);
  const estimatedTax = cartRows.reduce((total, row) => total + Math.round(row.quantity * row.product!.salePrice * row.product!.gstRate) / 100, 0);
  const quantityFor = (productId: number) => cart.find(line => line.itemId === productId)?.quantity || 0;
  const setQuantity = (product: Product, raw: number) => {
    const quantity = Math.max(0, Math.round(raw * 1000) / 1000);
    if (product.available !== null && quantity > product.available) { setError(`Only ${product.available} ${product.uom} available for ${product.name}`); return; }
    setError('');
    setCart(previous => quantity === 0 ? previous.filter(line => line.itemId !== product.id) : previous.some(line => line.itemId === product.id) ? previous.map(line => line.itemId === product.id ? { ...line, quantity } : line) : [...previous, { itemId: product.id, quantity }]);
  };
  const placeOrder = async () => {
    setError(''); setSubmitting(true);
    try {
      const response = await fetch('/api/backend/storefront/orders', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ ...buyer, lines: cart.map(line => ({ itemId: line.itemId, quantity: line.quantity })) }) });
      const data = await response.json();
      if (!response.ok) throw new Error(Array.isArray(data.message) ? data.message.join(', ') : data.message || 'Order could not be placed');
      setResult(data); setCart([]); setCheckoutOpen(false); setBuyer(initialCheckout);
      await refetch();
    } catch (cause) { setError(cause instanceof Error ? cause.message : 'Order could not be placed'); }
    finally { setSubmitting(false); }
  };
  const switchLanguage = () => { const next = language === 'en' ? 'ta' : 'en'; setLanguage(next); localStorage.setItem('shop-language', next); };

  return <Box sx={{ minHeight: '100vh', bgcolor: '#f7f5ef', color: '#172820' }}>
    <Box sx={{ bgcolor: '#153e32', color: 'white', py: 1.2 }}><Container maxWidth="xl"><Stack direction="row" justifyContent="space-between" alignItems="center"><Typography variant="body2">EverGreen × Weave</Typography><Typography variant="body2">{t.tagline}</Typography></Stack></Container></Box>
    <Container maxWidth="xl" sx={{ py: 2 }}><Stack direction="row" alignItems="center" justifyContent="space-between" spacing={2}><Stack direction="row" alignItems="center" spacing={1}><ShoppingBag sx={{ color: '#177857' }} /><Typography variant="h5" fontWeight={900}>EverGreen <Box component="span" sx={{ color: '#16835d' }}>Weave</Box></Typography></Stack><Stack direction="row" alignItems="center" spacing={1}><Button color="inherit" onClick={switchLanguage}>{language === 'en' ? 'தமிழ்' : 'English'}</Button><Button color="inherit" href="/">{t.staff}</Button><Chip icon={<ShoppingCart />} label={cart.length} color="success" /></Stack></Stack></Container>
    <Box sx={{ background: 'linear-gradient(120deg, #e6eee4 0%, #f4e8d5 100%)', py: { xs: 5, md: 8 } }}><Container maxWidth="xl"><Typography variant="overline" fontWeight={800} color="success.dark">{t.collection}</Typography><Typography variant="h2" sx={{ fontWeight: 900, maxWidth: 700, fontSize: { xs: '2.3rem', md: '4rem' }, lineHeight: 1.08, mt: 1 }}>{t.hero}</Typography><Typography sx={{ maxWidth: 570, mt: 2, fontSize: '1.1rem' }}>{t.intro}</Typography></Container></Box>
    <Container maxWidth="xl" sx={{ py: 4 }}>
      <Stack direction={{ xs: 'column', md: 'row' }} spacing={2} sx={{ mb: 3 }}><TextField label={t.search} value={search} onChange={event => setSearch(event.target.value)} InputProps={{ startAdornment: <Search sx={{ mr: 1, color: '#719084' }} /> }} sx={{ flex: 2 }} /><TextField select label={t.all} value={category} onChange={event => setCategory(event.target.value)} sx={{ flex: 1 }}><MenuItem value="">{t.all}</MenuItem>{categories.map(value => <MenuItem key={value} value={value}>{value}</MenuItem>)}</TextField><TextField select label={t.allBrands} value={brand} onChange={event => setBrand(event.target.value)} sx={{ flex: 1 }}><MenuItem value="">{t.allBrands}</MenuItem>{brands.map(value => <MenuItem key={value} value={value}>{value}</MenuItem>)}</TextField><TextField select label={t.sort} value={sort} onChange={event => setSort(event.target.value)} sx={{ flex: 1 }}><MenuItem value="name">{t.newest}</MenuItem><MenuItem value="low">{t.priceLow}</MenuItem><MenuItem value="high">{t.priceHigh}</MenuItem></TextField></Stack>
      {error && !checkoutOpen && <Paper role="alert" sx={{ p: 2, mb: 2, color: '#ad2f2f' }}>{error}</Paper>}
      {isError && <Paper sx={{ p: 4, textAlign: 'center' }}><Typography>{t.loadError}</Typography><Button onClick={() => void refetch()}>{t.retry}</Button></Paper>}
      {!isLoading && !isError && !filtered.length && <Paper sx={{ p: 5, textAlign: 'center' }}><Typography>{products.length ? t.noMatch : t.noProducts}</Typography></Paper>}
      <Grid container spacing={3}>
        {filtered.map(product => <Grid key={product.id} size={{ xs: 12, sm: 6, lg: 4, xl: 3 }}><Paper elevation={0} sx={{ borderRadius: 3, overflow: 'hidden', height: '100%', border: '1px solid #d9e1d9' }}><Box sx={{ height: 190, display: 'grid', placeItems: 'center', bgcolor: '#e5e8df', background: 'radial-gradient(circle at 20% 20%, #f6e5bf, transparent 40%), radial-gradient(circle at 80% 80%, #a7d3bc, transparent 45%), #e5e8df' }}><Inventory2 sx={{ fontSize: 82, color: '#477664', opacity: 0.72 }} /></Box><Box sx={{ p: 2.5 }}><Stack direction="row" justifyContent="space-between"><Typography variant="overline" color="success.dark">{product.brand || 'EVERGREEN'}</Typography>{product.category && <Chip size="small" label={product.category} />}</Stack><Typography variant="h6" fontWeight={800}>{product.name}</Typography><Typography variant="caption" color="text.secondary">{product.sku}</Typography><Typography sx={{ minHeight: 42, mt: 1 }} variant="body2" color="text.secondary">{product.description?.slice(0, 95) || product.type.replaceAll('_', ' ')}</Typography><Stack direction="row" justifyContent="space-between" alignItems="end" sx={{ mt: 2 }}><Box><Typography variant="h6" fontWeight={900}>{money(product.salePrice)}</Typography><Typography variant="caption">+ {product.gstRate}% {t.gst}</Typography></Box><Typography variant="caption">{product.available === null ? t.service : `${product.available} ${product.uom} ${t.available}`}</Typography></Stack><Stack direction="row" spacing={1} sx={{ mt: 2 }}><Button variant="outlined" onClick={() => setSelected(product)}>{t.view}</Button><Button variant="contained" color="success" disabled={product.available !== null && product.available <= 0} onClick={() => setQuantity(product, quantityFor(product.id) + 1)} startIcon={<Add />} sx={{ flex: 1 }}>{t.add}</Button></Stack></Box></Paper></Grid>)}
      </Grid>
    </Container>
    <Container maxWidth="xl" sx={{ pb: 5 }}><Paper elevation={2} sx={{ p: { xs: 2, md: 3 }, borderRadius: 3 }}><Stack direction={{ xs: 'column', md: 'row' }} justifyContent="space-between" spacing={3}><Box sx={{ flex: 1 }}><Stack direction="row" spacing={1} alignItems="center"><ShoppingCart color="success" /><Typography variant="h5" fontWeight={800}>{t.cart}</Typography></Stack>{cartRows.length ? cartRows.map(row => <Stack key={row.itemId} direction="row" alignItems="center" spacing={1} sx={{ py: 1.5, borderBottom: '1px solid #e6e6e6' }}><Typography sx={{ flex: 1 }} fontWeight={600}>{row.product!.name}</Typography><IconButton aria-label={`Remove ${row.product!.name}`} onClick={() => setQuantity(row.product!, row.quantity - 1)}><Remove /></IconButton><TextField type="number" size="small" value={row.quantity} onChange={event => setQuantity(row.product!, Number(event.target.value))} inputProps={{ min: 0, max: row.product!.available ?? undefined, step: 0.001, 'aria-label': `${row.product!.name} quantity` }} sx={{ width: 100 }} /><IconButton aria-label={`Add ${row.product!.name}`} onClick={() => setQuantity(row.product!, row.quantity + 1)}><Add /></IconButton><Typography sx={{ width: 100, textAlign: 'right' }}>{money(row.quantity * row.product!.salePrice)}</Typography></Stack>) : <Typography sx={{ my: 3 }} color="text.secondary">{t.empty}</Typography>}</Box><Box sx={{ minWidth: { md: 300 } }}><Typography>{t.subtotal}: {money(subtotal)}</Typography><Typography>{t.estimatedTax}: {money(estimatedTax)}</Typography><Divider sx={{ my: 1 }} /><Typography variant="h6" fontWeight={800}>{t.estimatedTotal}: {money(subtotal + estimatedTax)}</Typography><Button variant="contained" color="success" size="large" fullWidth disabled={!cart.length} onClick={() => { setError(''); setCheckoutOpen(true); }} sx={{ mt: 2 }}>{t.checkout}</Button></Box></Stack></Paper></Container>
    <Box sx={{ bgcolor: '#153e32', color: 'white', py: 3 }}><Container maxWidth="xl"><Stack direction={{ xs: 'column', sm: 'row' }} spacing={1} justifyContent="space-between"><Typography>EverGreen Weave</Typography><Stack direction="row" spacing={1}><LocalShipping fontSize="small" /><Typography variant="body2">{t.paymentNotice}</Typography></Stack></Stack></Container></Box>
    <Dialog open={!!selected} onClose={() => setSelected(null)} fullWidth maxWidth="sm"><DialogTitle>{selected?.name}<IconButton onClick={() => setSelected(null)} sx={{ float: 'right' }}><Close /></IconButton></DialogTitle><DialogContent><Typography color="text.secondary">{selected?.description || selected?.type.replaceAll('_', ' ')}</Typography><Typography sx={{ mt: 2 }}>{t.sku}: {selected?.sku}</Typography><Typography>{selected?.available === null ? t.service : `${selected?.available} ${selected?.uom} ${t.available}`}</Typography><Typography variant="h6" sx={{ mt: 2 }}>{money(selected?.salePrice || 0)} + {selected?.gstRate}% {t.gst}</Typography><Button variant="contained" color="success" sx={{ mt: 2 }} onClick={() => { if (selected) setQuantity(selected, quantityFor(selected.id) + 1); setSelected(null); }}>{t.add}</Button></DialogContent></Dialog>
    <Dialog open={checkoutOpen} onClose={() => !submitting && setCheckoutOpen(false)} fullWidth maxWidth="sm"><DialogTitle><Stack direction="row" alignItems="center" justifyContent="space-between"><Typography variant="h6">{t.details}</Typography><IconButton onClick={() => setCheckoutOpen(false)} disabled={submitting}><Close /></IconButton></Stack></DialogTitle><DialogContent><Stack spacing={2} sx={{ pt: 1 }}><TextField label={t.name} required value={buyer.name} onChange={event => setBuyer({ ...buyer, name: event.target.value })} /><TextField label={t.phone} required value={buyer.phone} onChange={event => setBuyer({ ...buyer, phone: event.target.value })} /><TextField label={t.email} type="email" value={buyer.email} onChange={event => setBuyer({ ...buyer, email: event.target.value })} /><TextField label={t.address} required multiline minRows={2} value={buyer.address} onChange={event => setBuyer({ ...buyer, address: event.target.value })} /><TextField select label={t.state} required value={buyer.state} onChange={event => setBuyer({ ...buyer, state: event.target.value })}>{states.map(value => <MenuItem key={value} value={value}>{value}</MenuItem>)}</TextField><TextField label={t.gstin} value={buyer.gstin} onChange={event => setBuyer({ ...buyer, gstin: event.target.value })} /><TextField label={t.notes} value={buyer.notes} onChange={event => setBuyer({ ...buyer, notes: event.target.value })} multiline /><input tabIndex={-1} autoComplete="off" aria-hidden="true" name="website" value={buyer.website} onChange={event => setBuyer({ ...buyer, website: event.target.value })} style={{ position: 'absolute', left: '-9999px' }} />{error && <Typography role="alert" color="error">{error}</Typography>}<Typography variant="body2">{t.estimatedTotal}: {money(subtotal + estimatedTax)}. {t.paymentNotice}</Typography><Button variant="contained" color="success" size="large" disabled={submitting || !buyer.name.trim() || !buyer.phone.trim() || !buyer.address.trim()} onClick={() => void placeOrder()}>{submitting ? t.placing : t.place}</Button></Stack></DialogContent></Dialog>
    <Dialog open={!!result} onClose={() => setResult(null)} fullWidth maxWidth="sm"><DialogContent sx={{ textAlign: 'center', py: 5 }}><CheckCircle color="success" sx={{ fontSize: 72 }} /><Typography variant="h5" fontWeight={800} sx={{ mt: 1 }}>{t.success}</Typography><Typography sx={{ mt: 1 }}>{t.orderNo}: <strong>{result?.orderNo}</strong></Typography><Typography sx={{ mt: 1 }}>{t.estimatedTotal}: {money(result?.estimatedTotal || 0)}</Typography><Typography color="text.secondary" sx={{ mt: 2 }}>{t.successNote}</Typography><Button startIcon={<ArrowBack />} sx={{ mt: 3 }} onClick={() => setResult(null)}>{t.back}</Button></DialogContent></Dialog>
  </Box>;
}
