import { useMemo, useState } from 'react';
import { Alert, Box, Button, Chip, Dialog, DialogActions, DialogContent, DialogTitle, Divider, FormControlLabel, MenuItem, Paper, Stack, Switch, Tab, Tabs, Table, TableBody, TableCell, TableContainer, TableHead, TableRow, TextField, Typography } from '@mui/material';
import Grid from '@mui/material/GridLegacy';
import { AccountTree, Add, ArrowForward, Lock, ReceiptLong, VerifiedUser } from '@mui/icons-material';
import { useQuery } from '@tanstack/react-query';
import { toast } from 'sonner';
import api from '../utils/api';
import { downloadWorkflowDocument } from '../utils/workflowDocument';

type Field = { key: string; label: string; source?: string; type?: string; required?: boolean };
type Operation = { kind: string; title: string; group: string; description: string; fields: Field[]; lines?: 'item' | 'source' | 'invoice'; physical?: boolean };
const field = (key: string, label: string, source?: string, type?: string): Field => ({ key, label, source, type });
const operations: Operation[] = [
  { kind: 'CANCEL_ORDER', group: 'Sales & money', title: 'Cancel remaining sales order', description: 'Close the outstanding requirement and release its actual reservations, preserving delivered and billed goods.', fields: [field('orderId', 'Open / held order', 'cancelOrders')] },
  { kind: 'RESUME_ORDER', group: 'Sales & money', title: 'Resume order after quality review', description: 'Reserve its outstanding quantities again from released stock before resuming delivery.', fields: [field('orderId', 'Held sales order', 'heldOrders')] },
  { kind: 'LINK_COTTON_RECEIPT', group: 'Purchases & payables', title: 'Bill an existing cotton receipt', description: 'Link an original batch receipt to supplier accounting, with verified cost evidence. Quantity is not received twice.', fields: [field('inwardId', 'Original cotton receipt', 'inwardBatches'), field('supplierId', 'Supplier', 'suppliers'), field('rate', 'Verified unit cost ₹', undefined, 'number'), field('gstRate', 'Bill GST %', undefined, 'number')] },
  { kind: 'AMEND_ORDER', group: 'Sales & money', title: 'Amend agreed order discount', description: 'Change commercial terms before delivery or invoicing. Later returns use linked credits.', fields: [field('orderId', 'Sales order', 'orders'), field('discount', 'New order discount ₹', undefined, 'number')] },
  { kind: 'COST_CORRECTION', group: 'Stock & control', title: 'Correct a posted expense', description: 'Append a signed expense correction while retaining the original accounting record.', fields: [field('costingEntryId', 'Original expense', 'costs'), field('amount', 'Correction ₹ (+ increase / − decrease)', undefined, 'number')] },
  { kind: 'CUSTOMER_UNALLOCATE', group: 'Sales & money', title: 'Reverse credit allocation', description: 'Restore the original credit and target invoice balance without moving stock or cash.', fields: [field('originId', 'Original allocation', 'allocations')] },
  { kind: 'SUPPLIER_CREDIT_ALLOCATION', group: 'Purchases & payables', title: 'Allocate supplier return credit', description: 'Move paid return credit to another bill or conversion charge from the same supplier.', fields: [field('originId', 'Supplier return credit', 'supplierCredits'), field('billId', 'Bill / work charge to settle', 'payables'), field('amount', 'Allocation ₹', undefined, 'number')] },
  { kind: 'SUPPLIER_REFUND', group: 'Purchases & payables', title: 'Refund received from supplier', description: 'Record money actually returned by the supplier after a paid purchase return.', fields: [field('originId', 'Supplier return credit', 'supplierCredits'), field('amount', 'Refund received ₹', undefined, 'number')] },
  { kind: 'PURCHASE_ORDER_CANCEL', group: 'Purchases & payables', title: 'Cancel purchase remainder', description: 'Close further supply while preserving receipts, bills and payments already posted.', fields: [field('originId', 'Purchase order', 'purchaseOrders')] },
  { kind: 'SALES_RETURN', group: 'Sales & money', title: 'Partial sales return', description: 'Receive goods against their invoice lines, quarantine damaged quantities and issue a linked tax credit.', fields: [field('invoiceId', 'Original invoice', 'invoices')], lines: 'invoice', physical: true },
  { kind: 'CUSTOMER_RECEIPT', group: 'Sales & money', title: 'Customer advance', description: 'Record an advance or excess receipt; allocate it across invoices later.', fields: [field('customerId', 'Customer', 'customers'), field('amount', 'Amount received ₹', undefined, 'number'), field('reference', 'Bank / receipt reference')] },
  { kind: 'CUSTOMER_ALLOCATION', group: 'Sales & money', title: 'Allocate customer credit', description: 'Use an advance or refundable return credit to settle another invoice.', fields: [field('originId', 'Credit / advance', 'customerCredits'), field('invoiceId', 'Invoice to settle', 'invoices'), field('amount', 'Allocation ₹', undefined, 'number')] },
  { kind: 'CUSTOMER_REFUND', group: 'Sales & money', title: 'Customer refund', description: 'Record money actually refunded from unused advance or return credit.', fields: [field('originId', 'Credit / advance', 'customerCredits'), field('amount', 'Refund ₹', undefined, 'number'), field('reference', 'Refund reference')] },
  { kind: 'ORDER_DISPATCH', group: 'Sales & money', title: 'Dispatch reserved order', description: 'Release this order’s reservation and deliver once. Bill the dispatch separately.', fields: [field('orderId', 'Sales order', 'orders')], lines: 'source' },
  { kind: 'INVOICE_DISPATCH', group: 'Sales & money', title: 'Bill order dispatch', description: 'Invoice delivered quantities without another stock deduction.', fields: [field('originId', 'Order dispatch', 'dispatches'), field('documentNo', 'Invoice number (optional)')], lines: 'source' },
  { kind: 'DISPATCH_RETURN', group: 'Sales & money', title: 'Return unbilled dispatch', description: 'Receive the original dispatch back. Billed goods use partial sales return.', fields: [field('originId', 'Order dispatch', 'dispatches')], physical: true },
  { kind: 'PURCHASE_ORDER', group: 'Purchases & payables', title: 'Purchase order', description: 'Agree item quantities, unit costs and tax with a supplier.', fields: [field('supplierId', 'Supplier', 'suppliers')], lines: 'item' },
  { kind: 'GOODS_RECEIPT', group: 'Purchases & payables', title: 'Receive purchase', description: 'Receive a partial purchase order into traceable company lots.', fields: [field('originId', 'Purchase order', 'purchaseOrders')], lines: 'source' },
  { kind: 'SUPPLIER_BILL', group: 'Purchases & payables', title: 'Supplier bill', description: 'Bill receipt quantities or agreed purchase-order services; create payable and input-tax entries.', fields: [field('originId', 'Goods receipt / service order', 'billSources'), field('documentNo', 'Supplier bill reference')], lines: 'source' },
  { kind: 'PURCHASE_RETURN', group: 'Purchases & payables', title: 'Return to supplier', description: 'Return original received lots and debit the linked supplier bill.', fields: [field('originId', 'Supplier bill', 'bills')], lines: 'source', physical: true },
  { kind: 'SUPPLIER_PAYMENT', group: 'Purchases & payables', title: 'Supplier payment / advance', description: 'Record payment to a supplier, retaining unallocated credit.', fields: [field('supplierId', 'Supplier', 'suppliers'), field('amount', 'Amount paid ₹', undefined, 'number')] },
  { kind: 'SUPPLIER_ALLOCATION', group: 'Purchases & payables', title: 'Allocate supplier payment', description: 'Settle a supplier bill or conversion work charge from its unallocated payment balance.', fields: [field('originId', 'Supplier payment', 'supplierPayments'), field('billId', 'Supplier bill / work charge', 'payables'), field('amount', 'Allocation ₹', undefined, 'number')] },
  { kind: 'WIP_COMPLETION', group: 'Manufacturing', title: 'Complete intermediate stock', description: 'Convert part of a WIP lot into output, with explicit process loss.', fields: [field('wipId', 'Intermediate lot', 'wip'), field('quantity', 'WIP consumed kg', undefined, 'number'), field('loss', 'Process loss kg', undefined, 'number'), field('processingCost', 'Allocated process cost ₹', undefined, 'number')], lines: 'item' },
  { kind: 'TRANSFORM_DISPATCH', group: 'Manufacturing', title: 'Send conversion job', description: 'Supply inputs to a job worker and agree output, yield tolerance and work charge.', fields: [field('supplierId', 'Job worker', 'suppliers'), field('outputItemId', 'Expected output item', 'items'), field('expectedOutput', 'Expected output quantity', undefined, 'number'), field('yieldTolerance', 'Yield tolerance %', undefined, 'number'), field('charge', 'Agreed work charge ₹', undefined, 'number'), field('process', 'Process / style')], lines: 'item' },
  { kind: 'TRANSFORM_RECEIPT', group: 'Manufacturing', title: 'Receive converted output', description: 'Account for consumed supplied material, output, loss and partial work charges.', fields: [field('originId', 'Conversion job', 'jobs'), field('outputQuantity', 'Output received', undefined, 'number'), field('loss', 'Loss / scrap', undefined, 'number'), field('charge', 'Work charge for this receipt ₹', undefined, 'number')], lines: 'source' },
  { kind: 'TRANSFORM_CANCEL', group: 'Manufacturing', title: 'Close & return job material', description: 'Return only the job’s outstanding original inputs; keep completed receipts and losses.', fields: [field('originId', 'Conversion job', 'jobs')], physical: true },
  { kind: 'QUALITY_HOLD', group: 'Stock & control', title: 'Quarantine a lot', description: 'Block a specific quantity from production, reservation and shipment.', fields: [field('lotId', 'Stock lot', 'lots'), field('quantity', 'Quantity to hold', undefined, 'number')] },
  { kind: 'LOT_RECLASSIFY', group: 'Stock & control', title: 'Identify a variant lot', description: 'Trace colour and grade within the original item without creating company stock.', fields: [field('lotId', 'Source lot', 'lots'), field('quantity', 'Quantity', undefined, 'number'), field('lotCode', 'New lot identity'), field('grade', 'Grade'), field('colour', 'Colour')] },
  { kind: 'PICK', group: 'Stock & control', title: 'Pick for packing', description: 'Release physical stock from warehouse locations against an order before dispatch.', fields: [field('orderId', 'Sales order', 'orders')], lines: 'item' },
  { kind: 'VALUATION', group: 'Stock & control', title: 'Set verified receipt cost', description: 'Set one external receipt’s evidenced cost. Derived production and return costs follow their original material.', fields: [field('movementId', 'Original unvalued receipt', 'unvaluedReceipts'), field('rate', 'Verified cost per unit ₹', undefined, 'number')] },
];
const titleCase = (s: string) => s.toLowerCase().replaceAll('_', ' ').replace(/(^|\s)\S/g, c => c.toUpperCase());
const fmt = (n: unknown) => Number(n || 0).toLocaleString('en-IN', { maximumFractionDigits: 2 });

export default function WorkflowDesk({ initialTab = 0 }: { initialTab?: number } = {}) {
  const { data, isLoading, error } = useQuery<any>({ queryKey: ['workflows'], queryFn: async () => (await api.get('/workflows')).data });
  const [tab, setTab] = useState(initialTab), [operation, setOperation] = useState<Operation | null>(null), [form, setForm] = useState<any>({}), [lines, setLines] = useState<any[]>([]), [saving, setSaving] = useState(false), [requestKey, setRequestKey] = useState(''), [selectedDoc, setSelectedDoc] = useState<any>(null);
  const [supplierOpen, setSupplierOpen] = useState(false), [supplier, setSupplier] = useState({ name: '', code: '', gstin: '', address: '' }), [release, setRelease] = useState<any>(null), [releaseNotes, setReleaseNotes] = useState(''), [closeOpen, setCloseOpen] = useState(false), [closeDate, setCloseDate] = useState(''), [closeNotes, setCloseNotes] = useState('');
  const user = useMemo(() => { try { return JSON.parse(localStorage.getItem('user') || '{}'); } catch { return {}; } }, []);
  const canWrite = ['ADMIN', 'MODIFIER'].includes(user.role), docs = data?.documents || [];
  const byKind = (kind: string) => docs.filter((d: any) => d.kind === kind && !['CANCELLED', 'RETURNED', 'COMPLETED'].includes(d.status));
  const sources: Record<string, any[]> = { suppliers: data?.suppliers || [], customers: data?.customers || [], invoices: data?.invoices || [], orders: (data?.orders || []).filter((o: any) => ['CONFIRMED', 'PARTIALLY_INVOICED'].includes(o.status)), items: data?.items || [], lots: (data?.lots || []).filter((l: any) => l.quantity > 0), wip: (data?.wip || []).filter((l: any) => l.status === 'OPEN'), customerCredits: [...byKind('CUSTOMER_RECEIPT'), ...byKind('SALES_RETURN')], supplierPayments: byKind('SUPPLIER_PAYMENT'), purchaseOrders: byKind('PURCHASE_ORDER'), receipts: byKind('GOODS_RECEIPT'), bills: byKind('SUPPLIER_BILL'), dispatches: byKind('ORDER_DISPATCH'), jobs: byKind('TRANSFORM_DISPATCH') };
  const label = (r: any) => r.documentNo || r.invoiceNo || r.orderNo || (r.code ? `${r.code} · ${r.item?.name || r.name || ''}` : r.name);
  sources.allocations = byKind('CUSTOMER_ALLOCATION').filter((d: any) => d.status !== 'REVERSED');
  sources.supplierCredits = byKind('PURCHASE_RETURN');
  sources.payables = [...sources.bills, ...byKind('TRANSFORM_RECEIPT')];
  sources.unvaluedReceipts = (data?.valuation.missing || []).map((v: any) => v.movement).filter((m: any) => m.quantity > 0 && !['WIP_COMPLETION', 'TRANSFORM_RECEIPT', 'TRANSFORM_CANCEL', 'SALES_RETURN', 'DISPATCH_RETURN', 'JOB_WORK', 'LEGACY_YARN'].includes(m.referenceType) && m.movementType !== 'INVOICE_REVERSAL').map((m: any) => ({ ...m, name: `${m.item.name} · ${m.referenceType || m.movementType} ${m.referenceId || ''} · ${fmt(m.quantity)} · ${new Date(m.date).toLocaleDateString('en-IN')}` }));
  sources.costs = (data?.costs || []).map((c: any) => ({ ...c, name: `${c.category} · ${fmt(c.totalCost)} · ${new Date(c.date).toLocaleDateString('en-IN')}` }));
  sources.inwardBatches = (data?.inwardBatches || []).filter((b: any) => !b.isMerged && !b.catalogueItemId).map((b: any) => ({ ...b, name: `${b.batchId} · ${b.supplier} · ${fmt(b.kg)} kg` }));
  sources.receipts = [...sources.receipts, ...byKind('LINK_COTTON_RECEIPT')];
  sources.billSources = [...sources.receipts, ...sources.purchaseOrders.filter((d: any) => d.lines.some((l: any) => l.item?.type === 'SERVICE'))];
  sources.heldOrders = (data?.orders || []).filter((o: any) => o.status === 'ON_HOLD');
  sources.cancelOrders = (data?.orders || []).filter((o: any) => ['CONFIRMED', 'PARTIALLY_INVOICED', 'ON_HOLD'].includes(o.status));
  const open = (op: Operation) => { setOperation(op); setRequestKey(crypto.randomUUID()); setForm({ date: '', notes: '', returnConfirmed: false, loss: '0', yieldTolerance: '5', processingCost: '0' }); setLines(op.lines === 'item' ? [{ itemId: '', quantity: '', rate: '', gstRate: '' }] : []); };
  const change = (key: string, value: any) => {
    setForm((f: any) => ({ ...f, [key]: value }));
    if (!operation?.lines || !['originId', 'invoiceId', 'orderId'].includes(key) || operation.lines === 'item') return;
    const source = key === 'invoiceId' ? sources.invoices.find((d: any) => d.id === Number(value)) : key === 'orderId' ? sources.orders.find((d: any) => d.id === Number(value)) : docs.find((d: any) => d.id === Number(value));
    const sourceLines = (source?.items || source?.lines || []).filter((l: any) => operation.kind !== 'SUPPLIER_BILL' || source.kind !== 'PURCHASE_ORDER' || l.item?.type === 'SERVICE');
    setLines(sourceLines.filter((l: any) => l.direction !== 'IN' || operation.kind !== 'TRANSFORM_RECEIPT').map((l: any) => ({ itemId: l.itemId, invoiceItemId: key === 'invoiceId' ? l.id : undefined, sourceLineId: key !== 'invoiceId' ? l.id : undefined, quantity: '', rejectedQty: '0', rate: String(l.rate || 0), gstRate: String(l.gstRate || 0), lotId: l.lotId || '', description: l.item?.name || l.description, maximum: l.quantity - Number(l.invoicedQty || 0) })));
  };
  const submit = async () => {
    if (!operation || saving) return;
    if (operation.kind === 'PURCHASE_ORDER' && lines.some(l => Number(l.quantity) > 0 && (l.rate === '' || l.rate === undefined))) { toast.error('Enter the agreed unit cost for each purchase line'); return; }
    setSaving(true);
    try {
      const payload: any = { ...form, date: form.date ? new Date(form.date).toISOString() : undefined, requestKey, lines: lines.filter(l => Number(l.quantity) > 0).map(({ description, maximum, ...l }) => ({ ...l, quantity: Number(l.quantity), rate: Number(l.rate || 0), gstRate: Number(l.gstRate || 0), rejectedQty: Number(l.rejectedQty || 0), lotId: l.lotId ? Number(l.lotId) : undefined, locationId: l.locationId ? Number(l.locationId) : undefined })) };
      if (operation.kind === 'INVOICE_DISPATCH') {
        const source = docs.find((d: any) => d.id === Number(form.originId));
        await api.post('/commerce/invoices', { customerId: source?.customerId, fulfilmentId: source?.id, invoiceNo: form.documentNo || undefined, date: payload.date, requestKey, notes: form.notes, lines: payload.lines.map((l: any) => ({ itemId: l.itemId, quantity: l.quantity, rate: l.rate })) });
      } else if (operation.kind === 'AMEND_ORDER') await api.post(`/workflows/orders/${form.orderId}/amend`, { discount: Number(form.discount), notes: form.notes });
      else if (operation.kind === 'CANCEL_ORDER') await api.post(`/commerce/orders/${form.orderId}/cancel`, { notes: form.notes });
      else await api.post(`/workflows/post/${operation.kind}`, payload);
      setOperation(null); toast.success('Posted. Stock, documents and accounts updated together.');
    } catch (e: any) { toast.error(e.response?.data?.message || 'Could not post this operation'); } finally { setSaving(false); }
  };
  const changeLine = (index: number, key: string, value: any) => setLines(old => old.map((l, i) => i === index ? { ...l, [key]: value } : l));
  const handleRelease = async () => { setSaving(true); try { await api.post(`/workflows/holds/${release.id}/release`, { notes: releaseNotes }); setRelease(null); toast.success('Inspection recorded and stock released'); } catch (e: any) { toast.error(e.response?.data?.message || 'Release failed'); } finally { setSaving(false); } };
  if (isLoading) return <Typography>Loading business flows…</Typography>;
  if (error) return <Alert severity="error">Business flows could not be loaded.</Alert>;
  return <Box sx={{ maxWidth: 1400, mx: 'auto' }}>
    <Paper variant="outlined" sx={{ p: { xs: 2, md: 3 }, borderRadius: 4, mb: 3, borderTop: '4px solid', borderTopColor: 'primary.main' }}>
      <Stack direction="row" spacing={2} alignItems="center"><AccountTree color="primary" sx={{ fontSize: 40 }} /><Box sx={{ flex: 1 }}><Typography variant="overline" color="primary">EVERGREEN · CONNECTED OPERATIONS</Typography><Typography variant="h4" fontWeight={800}>Business flows</Typography><Typography color="text.secondary">Follow material, documents and money from receipt to return.</Typography></Box>{canWrite && <Button startIcon={<Add />} onClick={() => setSupplierOpen(true)}>Supplier / job worker</Button>}</Stack>
      <Stack direction="row" spacing={1} flexWrap="wrap" useFlexGap sx={{ mt: 2 }}><Chip label={`${docs.length} posted documents`} /><Chip label={`${(data?.wip || []).filter((w: any) => w.status === 'OPEN').length} open WIP lots`} /><Chip icon={<VerifiedUser />} label={`${(data?.lots || []).reduce((s: number, l: any) => s + l.holds.filter((h: any) => h.status === 'HELD').length, 0)} quality holds`} /><Chip label={data?.valuation.complete ? 'Stock costs reconciled' : `${data?.valuation.missing.length} movements need cost evidence`} color={data?.valuation.complete ? 'success' : 'warning'} /></Stack>
    </Paper>
    {canWrite && <Grid container spacing={2} sx={{ mb: 3 }}>{['Sales & money', 'Purchases & payables', 'Manufacturing', 'Stock & control'].map(group => <Grid item xs={12} md={6} lg={3} key={group}><Paper variant="outlined" sx={{ borderRadius: 3, p: 2, height: '100%' }}><Typography fontWeight={800} sx={{ mb: 1 }}>{group}</Typography><Stack spacing={0.5}>{operations.filter(o => o.group === group && (user.role === 'ADMIN' || !['CUSTOMER_REFUND', 'CUSTOMER_UNALLOCATE', 'COST_CORRECTION', 'DISPATCH_RETURN', 'TRANSFORM_CANCEL', 'AMEND_ORDER'].includes(o.kind))).map(op => <Button key={op.kind} color="inherit" endIcon={<ArrowForward fontSize="small" />} onClick={() => open(op)} sx={{ textTransform: 'none', justifyContent: 'space-between', textAlign: 'left' }}>{op.title}</Button>)}</Stack></Paper></Grid>)}</Grid>}
    <Tabs value={tab} onChange={(_, v) => setTab(v)} variant="scrollable"><Tab label="Document trail" /><Tab label="Lots, holds & WIP" /><Tab label="Accounts & closure" /></Tabs>
    {tab === 0 && <TableContainer component={Paper} variant="outlined" sx={{ mt: 2, borderRadius: 3 }}><Table><TableHead><TableRow>{['Document', 'Flow / source', 'Posted by', 'Date', 'Value', 'Status'].map(h => <TableCell key={h}>{h}</TableCell>)}</TableRow></TableHead><TableBody>{docs.map((d: any) => <TableRow key={d.id} hover><TableCell><Button onClick={() => setSelectedDoc(d)}>{d.documentNo}</Button></TableCell><TableCell>{titleCase(d.kind)}<Typography variant="caption" display="block" color="text.secondary">{d.originId ? docs.find((s: any) => s.id === d.originId)?.documentNo : d.invoiceId ? sources.invoices.find((i: any) => i.id === d.invoiceId)?.invoiceNo : ''}</Typography></TableCell><TableCell>{d.createdBy}</TableCell><TableCell>{new Date(d.date).toLocaleString('en-IN')}</TableCell><TableCell>₹{fmt(d.total)}</TableCell><TableCell><Chip size="small" label={d.status} /></TableCell></TableRow>)}{!docs.length && <TableRow><TableCell colSpan={6}>No business documents posted yet. Choose a flow above to begin with real source records.</TableCell></TableRow>}</TableBody></Table></TableContainer>}
    {tab === 1 && <Stack spacing={2} sx={{ mt: 2 }}><TableContainer component={Paper} variant="outlined"><Table size="small"><TableHead><TableRow>{['Lot identity / origin', 'Item / variant', 'On hand', 'Held', 'Quality decisions'].map(h => <TableCell key={h}>{h}</TableCell>)}</TableRow></TableHead><TableBody>{(data?.lots || []).map((l: any) => <TableRow key={l.id}><TableCell>{l.code}<Typography variant="caption" display="block">{l.origin}</Typography></TableCell><TableCell>{l.item.name}<Typography variant="caption" display="block">{[l.grade, l.colour, l.owner].filter(Boolean).join(' · ')}</Typography></TableCell><TableCell>{fmt(l.quantity)} {l.item.uom}</TableCell><TableCell>{fmt(l.held)}</TableCell><TableCell>{l.holds.filter((h: any) => h.status === 'HELD').map((h: any) => <Stack key={h.id} direction="row" spacing={1} alignItems="center"><Typography variant="body2">{fmt(h.quantity)} · {h.reason}</Typography>{canWrite && <Button size="small" onClick={() => { setRelease(h); setReleaseNotes(''); }}>Inspect & release</Button>}</Stack>)}</TableCell></TableRow>)}</TableBody></Table></TableContainer><Paper variant="outlined" sx={{ p: 2 }}><Typography fontWeight={800}>Intermediate stock</Typography>{(data?.wip || []).map((w: any) => <Stack key={w.id} direction="row" spacing={2} sx={{ mt: 1 }}><Typography>{w.code} · {fmt(w.remaining)} / {fmt(w.quantity)} kg · {w.unitCost === null ? 'Cost pending' : `₹${fmt(w.unitCost)}/kg`}</Typography><Chip size="small" label={w.status} /></Stack>)}{!data?.wip.length && <Typography color="text.secondary">Production with intermediate output creates a WIP lot here.</Typography>}</Paper></Stack>}
    {tab === 2 && <Stack spacing={2} sx={{ mt: 2 }}>{!data?.valuation.complete && <Alert severity="warning">Some receipt costs are unknown. Stock quantities remain valid; valuation and period closure need verified cost evidence.</Alert>}<TableContainer component={Paper} variant="outlined"><Table size="small"><TableHead><TableRow><TableCell>Account</TableCell><TableCell align="right">Debit ₹</TableCell><TableCell align="right">Credit ₹</TableCell><TableCell align="right">Balance ₹</TableCell></TableRow></TableHead><TableBody>{(data?.trialBalance || []).map((a: any) => <TableRow key={a.account}><TableCell>{titleCase(a.account)}</TableCell><TableCell align="right">{fmt(a.debit)}</TableCell><TableCell align="right">{fmt(a.credit)}</TableCell><TableCell align="right">{fmt(a.balance)}</TableCell></TableRow>)}{!data?.trialBalance.length && <TableRow><TableCell colSpan={4}>Financial postings will appear when documents or verified stock costs are recorded.</TableCell></TableRow>}</TableBody></Table></TableContainer><Paper variant="outlined" sx={{ p: 2 }}><Stack direction="row" justifyContent="space-between"><Typography fontWeight={800}>Accounting period locks</Typography>{user.role === 'ADMIN' && <Button startIcon={<Lock />} onClick={() => setCloseOpen(true)}>Close through a date</Button>}</Stack>{(data?.periods || []).map((p: any) => <Typography key={p.id}>Closed through {new Date(p.through).toLocaleDateString('en-IN')} · {p.closedBy} · {p.reason}</Typography>)}</Paper></Stack>}
    <Dialog open={!!operation} onClose={() => !saving && setOperation(null)} maxWidth="md" fullWidth><DialogTitle>{operation?.title}</DialogTitle><DialogContent><Stack spacing={2} sx={{ pt: 1 }}><Alert severity="info">{operation?.description}</Alert><Grid container spacing={2}>{operation?.fields.map(f => <Grid item xs={12} sm={6} key={f.key}><TextField fullWidth select={!!f.source} type={f.type || 'text'} label={f.label} value={form[f.key] ?? ''} onChange={e => change(f.key, f.source ? Number(e.target.value) : e.target.value)}>{f.source && [<MenuItem key="empty" value="">Select…</MenuItem>, ...(sources[f.source] || []).map(r => <MenuItem key={r.id} value={r.id}>{label(r)}</MenuItem>)]}</TextField></Grid>)}</Grid>
      {operation?.lines && <Box><Typography fontWeight={700} sx={{ mb: 1 }}>{operation.kind === 'TRANSFORM_RECEIPT' ? 'Supplied inputs consumed by this receipt' : 'Document lines'}</Typography><Stack spacing={1}>{lines.map((l, i) => <Paper variant="outlined" key={i} sx={{ p: 1.5, borderRadius: 2 }}><Grid container spacing={1}><Grid item xs={12} sm={4}>{operation.lines === 'item' ? <TextField select fullWidth label="Item" value={l.itemId} onChange={e => changeLine(i, 'itemId', Number(e.target.value))}>{sources.items.map(item => <MenuItem value={item.id} key={item.id}>{item.name} · {item.uom}</MenuItem>)}</TextField> : <Typography sx={{ pt: 1 }}>{l.description || sources.items.find(item => item.id === l.itemId)?.name}</Typography>}</Grid><Grid item xs={6} sm={2}><TextField fullWidth label="Quantity" type="number" value={l.quantity} onChange={e => changeLine(i, 'quantity', e.target.value)} /></Grid>{operation.kind === 'PURCHASE_ORDER' && <><Grid item xs={6} sm={2}><TextField fullWidth label="Unit cost ₹" type="number" value={l.rate} onChange={e => changeLine(i, 'rate', e.target.value)} /></Grid><Grid item xs={6} sm={2}><TextField fullWidth label="GST %" type="number" value={l.gstRate} onChange={e => changeLine(i, 'gstRate', e.target.value)} /></Grid></>}{operation.kind === 'SALES_RETURN' && <Grid item xs={6} sm={3}><TextField fullWidth label="Quarantine quantity" type="number" value={l.rejectedQty} onChange={e => changeLine(i, 'rejectedQty', e.target.value)} /></Grid>}{['ORDER_DISPATCH', 'TRANSFORM_DISPATCH'].includes(operation.kind) && <Grid item xs={12} sm={4}><TextField select fullWidth label="Lot (blank = available lots)" value={l.lotId || ''} onChange={e => changeLine(i, 'lotId', e.target.value)}><MenuItem value="">Choose available lots</MenuItem>{sources.lots.filter(lot => lot.itemId === l.itemId && lot.owner === 'COMPANY').map(lot => <MenuItem key={lot.id} value={lot.id}>{lot.code} · {fmt(lot.quantity - lot.held)}</MenuItem>)}</TextField></Grid>}{operation.kind === 'PICK' && <Grid item xs={12} sm={4}><TextField select fullWidth label="Location" value={l.locationId || ''} onChange={e => changeLine(i, 'locationId', Number(e.target.value))}>{(data?.locations || []).map((loc: any) => <MenuItem key={loc.id} value={loc.id}>{loc.name}</MenuItem>)}</TextField></Grid>}</Grid></Paper>)}</Stack>{operation.lines === 'item' && <Button onClick={() => setLines(old => [...old, { itemId: '', quantity: '', rate: '', gstRate: '' }])}>Add line</Button>}{!lines.length && <Typography color="text.secondary">Choose a source document to load its original lines.</Typography>}</Box>}
      <>{operation?.kind === 'PURCHASE_RETURN' && <FormControlLabel control={<Switch checked={form.returnHeldConfirmed === true} onChange={(_, checked) => change('returnHeldConfirmed', checked)} />} label="This supplier return includes quarantined goods" />}</><TextField label="Posting time (optional)" type="datetime-local" value={form.date || ''} onChange={e => change('date', e.target.value)} slotProps={{ inputLabel: { shrink: true } }} helperText="Blank uses the current time. Follow-up dates must be after their source; closed periods cannot be changed." /><TextField multiline minRows={2} label="Reason / evidence / notes" value={form.notes || ''} onChange={e => change('notes', e.target.value)} />{operation?.physical && <FormControlLabel control={<Switch checked={form.returnConfirmed === true} onChange={(_, checked) => change('returnConfirmed', checked)} />} label="I confirm the physical goods were received / returned" />}</Stack></DialogContent><DialogActions><Button disabled={saving} onClick={() => setOperation(null)}>Cancel</Button><Button variant="contained" disabled={saving} onClick={submit}>{saving ? 'Posting…' : 'Post & synchronize'}</Button></DialogActions></Dialog>
    <Dialog open={supplierOpen} onClose={() => !saving && setSupplierOpen(false)} maxWidth="sm" fullWidth><DialogTitle>Supplier / job worker</DialogTitle><DialogContent><Stack spacing={2} sx={{ pt: 1 }}>{Object.entries(supplier).map(([key, value]) => <TextField key={key} label={titleCase(key)} value={value} onChange={e => setSupplier(s => ({ ...s, [key]: e.target.value }))} />)}</Stack></DialogContent><DialogActions><Button onClick={() => setSupplierOpen(false)}>Cancel</Button><Button disabled={saving || !supplier.name.trim()} onClick={async () => { setSaving(true); try { await api.post('/workflows/suppliers', supplier); setSupplierOpen(false); setSupplier({ name: '', code: '', gstin: '', address: '' }); } catch (e: any) { toast.error(e.response?.data?.message || 'Could not save supplier'); } finally { setSaving(false); } }}>Save</Button></DialogActions></Dialog>
    <Dialog open={!!release} onClose={() => !saving && setRelease(null)} fullWidth maxWidth="sm"><DialogTitle>Inspect & release held stock</DialogTitle><DialogContent><Typography sx={{ mb: 2 }}>{fmt(release?.quantity)} · {release?.reason}</Typography><TextField fullWidth multiline label="Inspection result / release reason" value={releaseNotes} onChange={e => setReleaseNotes(e.target.value)} /></DialogContent><DialogActions><Button disabled={saving} onClick={() => setRelease(null)}>Cancel</Button><Button variant="contained" disabled={saving || !releaseNotes.trim()} onClick={handleRelease}>Record pass & release</Button></DialogActions></Dialog>
    <Dialog open={closeOpen} onClose={() => !saving && setCloseOpen(false)} fullWidth maxWidth="sm"><DialogTitle>Close accounting period</DialogTitle><DialogContent><Stack spacing={2} sx={{ pt: 1 }}><Alert severity="info">Stock costs must be complete and journals balanced. Historical postings are then locked; later corrections use an open period.</Alert><TextField type="date" label="Close through" value={closeDate} onChange={e => setCloseDate(e.target.value)} slotProps={{ inputLabel: { shrink: true } }} /><TextField multiline label="Closure reason" value={closeNotes} onChange={e => setCloseNotes(e.target.value)} /></Stack></DialogContent><DialogActions><Button onClick={() => setCloseOpen(false)}>Cancel</Button><Button disabled={saving || !closeDate || !closeNotes.trim()} onClick={async () => { setSaving(true); try { await api.post('/workflows/periods/close', { through: closeDate, notes: closeNotes }); setCloseOpen(false); } catch (e: any) { toast.error(e.response?.data?.message || 'Closure failed'); } finally { setSaving(false); } }}>Close period</Button></DialogActions></Dialog>
    <Dialog open={!!selectedDoc} onClose={() => setSelectedDoc(null)} fullWidth maxWidth="md"><DialogTitle><ReceiptLong sx={{ verticalAlign: 'middle', mr: 1 }} />{selectedDoc?.documentNo}</DialogTitle><DialogContent><Stack spacing={2}><Typography>{titleCase(selectedDoc?.kind || '')} · {selectedDoc?.status} · {selectedDoc && new Date(selectedDoc.date).toLocaleString('en-IN')}</Typography><Typography>{selectedDoc?.notes}</Typography><Divider /><Table size="small"><TableHead><TableRow><TableCell>Item</TableCell><TableCell>Origin line</TableCell><TableCell>Quantity</TableCell><TableCell>Net ₹</TableCell><TableCell>Tax ₹</TableCell></TableRow></TableHead><TableBody>{selectedDoc?.lines.map((l: any) => <TableRow key={l.id}><TableCell>{l.item?.name}</TableCell><TableCell>{l.sourceLineId || l.invoiceItemId || '—'}</TableCell><TableCell>{fmt(l.quantity)} {l.item?.uom}</TableCell><TableCell>{fmt(l.net)}</TableCell><TableCell>{fmt(l.tax)}</TableCell></TableRow>)}</TableBody></Table><Typography fontWeight={800}>Total ₹{fmt(selectedDoc?.total)}</Typography><Typography variant="caption">Posted by {selectedDoc?.createdBy}. Source and original quantities are retained.</Typography></Stack></DialogContent><DialogActions><Button onClick={() => downloadWorkflowDocument(selectedDoc)}>Download document PDF</Button><Button onClick={() => setSelectedDoc(null)}>Close</Button></DialogActions></Dialog>
  </Box>;
}
